name: dfs-lab01

services:
  web:
    image: python:3.11-slim
    volumes:
      - ./app.py:/app/app.py
    working_dir: /app
    command: ["python3", "app.py"]
    ports:
      # FIXED: Forwarding host 8080 to container 8000
      - "8080:8000"
