"""
Template Microservice Skeleton generated by Platform CLI.
"""

from fastapi import FastAPI, Response
from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

SERVICE_NAME = "{{service_name}}"

app = FastAPI(title=f"{{service_name}} Service", version="1.0.0")

REQUESTS_TOTAL = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["service", "method", "route", "status"]
)

REQUEST_DURATION_SECONDS = Histogram(
    "http_request_duration_seconds",
    "Request latency in seconds",
    ["service", "method", "route", "status"]
)


@app.get("/healthz")
def liveness():
    return {"status": "alive", "service": SERVICE_NAME}


@app.get("/ready")
def readiness():
    return {"status": "ready", "service": SERVICE_NAME}


@app.get("/metrics")
def metrics():
    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.get("/api/v1/resource")
def get_resource():
    REQUESTS_TOTAL.labels(service=SERVICE_NAME, method="GET", route="/api/v1/resource", status="200").inc()
    return {"message": "Hello from platform golden path", "service": SERVICE_NAME}
