"""
Phase metadata definitions for Part 1 (Phases 00 to 100).
"""

PHASES_PART_1 = [
    (0, "00-system-design-lab", "System Design Laboratory",
     "Set up a reproducible environment containing API servers, relational and caching layers, and load generators.",
     "System design requires empirical feedback loops to validate architectural hypotheses.",
     "One single Python process handling simulated requests.",
     "Add background metrics collector and local persistence.",
     "Simulated process crash under memory exhaustion.",
     "Local simulation does not capture physical multi-datacenter network jitter."),

    (1, "01-what-is-system-design", "What Is System Design?",
     "Differentiating code design, object-oriented design, backend architecture, and distributed system design.",
     "System design balances scale, state, communication, failures, and operational constraints.",
     "Single monolithic function performing computation.",
     "Separate client layer from application gateway and storage.",
     "Unbounded user concurrency stalling single thread.",
     "Decomposition introduces network communication overhead."),

    (2, "02-start-with-one-machine", "Start With One Machine",
     "Premature distribution creates distributed failure domains without scale justification.",
     "Do not distribute what does not need distribution. Measure single-node ceilings first.",
     "Client -> Monolithic App Server -> Single Database.",
     "Vertical resource increase (CPU, NVMe disk, RAM).",
     "High query volume exhausts database thread connections.",
     "Vertical scaling has a hard physical ceiling and single point of failure."),

    (3, "03-identify-bottlenecks", "Identify Bottlenecks",
     "Pinpointing whether CPU, memory, disk IOPS, or network bandwidth saturates first under traffic.",
     "Amdahl's law and resource saturation dictate system throughput limits.",
     "Single app instance connected to database under load.",
     "Instrument metrics to detect resource saturation points.",
     "Inject slow queries holding table locks.",
     "Profiling and telemetry introduce small compute and storage overheads."),

    (4, "04-latency-vs-throughput", "Latency vs Throughput",
     "Optimizing for batch throughput often increases individual request latency.",
     "Throughput = Operations per unit time; Latency = Time for a single operation.",
     "Synchronous per-item processing loop.",
     "Micro-batching requests to increase aggregate throughput.",
     "Large batch size induces high p99 latency spikes.",
     "Batching trades response immediacy for I/O efficiency."),

    (5, "05-percentiles", "Percentiles and Tail Latency",
     "Averages mask catastrophic latency spikes experienced by users at the tail.",
     "In systems with multi-component fanouts, p99 latency dominates user experience.",
     "Track mean request duration.",
     "Implement histogram tracking for p50, p95, and p99 latency.",
     "Inject skewed long-running queries.",
     "Percentile tracking requires sorted arrays or approximate streaming sketches (HdrHistogram)."),

    (6, "06-vertical-scaling", "Vertical Scaling",
     "Scaling up single-node hardware before adding distributed complexity.",
     "Bigger CPU and NVMe storage avoid network partitions, consensus, and distributed transactions.",
     "Single machine with 4 cores and 16 GB RAM.",
     "Scale vertically to 64 cores and 512 GB RAM.",
     "Physical host hardware failure brings down the entire system.",
     "High financial costs at the high end of server hardware; single failure domain."),

    (7, "07-horizontal-scaling", "Horizontal Scaling",
     "Adding multiple application instances to distribute incoming compute load.",
     "Stateless application compute scales linearly across commodity servers.",
     "Multiple independent application servers.",
     "Add load balancer in front of application instances.",
     "Clients send requests directly to single server IP, overloading it.",
     "Requires shared state externalization and network dispatch coordination."),

    (8, "08-load-balancers-from-first-principles", "Load Balancers From First Principles",
     "Building a reverse proxy that dispatches requests across backend instances with health checks.",
     "Layer 4 (Transport) vs Layer 7 (Application) proxy routing and failover.",
     "Client connecting directly to server IP.",
     "Reverse proxy with passive and active health checks.",
     "Backend instance crashes while proxy continues routing to it.",
     "Load balancer itself becomes a single point of failure unless paired in active-passive HA."),

    (9, "09-load-balancing-algorithms", "Load Balancing Algorithms",
     "Evaluating Round-Robin, Random, Least Connections, and IP Hash algorithms under skewed workloads.",
     "Workload duration variance determines the optimal routing policy.",
     "Round-robin dispatch.",
     "Least-connections routing adapting to long-lived connections.",
     "Long-running request monopolizes worker under naive round-robin.",
     "Least connections requires tracking global state across proxy threads."),

    (10, "10-stateless-services", "Stateless Services",
     "In-memory session state causes user logout when requests hit different app instances.",
     "Stateless compute enables arbitrary horizontal scaling and zero-downtime rolling deploys.",
     "Application server stores user session in local RAM.",
     "Externalize session state into centralized Redis / Memcached cluster.",
     "Server restart drops all active user sessions.",
     "External cache access adds network round-trip latency to every request."),

    (11, "11-reverse-proxy-and-gateway-concepts", "Reverse Proxy and Gateway Concepts",
     "Differentiating reverse proxies, L4/L7 load balancers, and API gateways.",
     "Separation of perimeter concerns: TLS termination, rate limiting, and route rewriting.",
     "Client directly talks to individual internal microservices.",
     "API Gateway centralizing authentication, routing, and throttling.",
     "API gateway CPU saturates under heavy cryptographic TLS handshakes.",
     "Gateway failure impacts all downstream services."),

    (12, "12-data-modeling-for-system-design", "Data Modeling for System Design",
     "Translating business requirements into entities, relationships, and access patterns.",
     "Access patterns (read-heavy vs write-heavy) must dictate schema normalization.",
     "Normalized 3NF relational schema.",
     "Denormalized read models for high-frequency lookup queries.",
     "Complex multi-table JOINs stall write transactions under load.",
     "Denormalization increases storage usage and requires multi-record write coordination."),

    (13, "13-database-choice-framework", "Database Choice Framework",
     "Choosing between Relational, Key-Value, Document, Wide-Column, and Search engines.",
     "Structure of data and query access patterns define datastore suitability.",
     "Defaulting to PostgreSQL for all access patterns.",
     "Polyglot persistence: PostgreSQL for ACID transactions, Redis for hot keys, ES for search.",
     "Executing full-text wildcard queries on relational tables causes table scans.",
     "Multiple datastores create operational overhead and distributed data sync challenges."),

    (14, "14-primary-keys", "Primary Keys in System Design",
     "Auto-increment integers vs UUIDs vs ULIDs in scalable databases.",
     "B-Tree index locality, fragmentation, security enumeration, and coordination cost.",
     "Sequential integer auto-increment keys.",
     "Time-sortable random IDs (UUIDv7, ULID) preventing enumeration and fragmentation.",
     "Random UUIDv4 causes random page writes and B-Tree split thrashing.",
     "128-bit UUIDs consume double the storage and index RAM of 64-bit integers."),

    (15, "15-distributed-id-generation", "Distributed ID Generation",
     "Generating 64-bit globally unique, time-ordered IDs across multi-datacenter clusters.",
     "Snowflake algorithm: Timestamp + Datacenter ID + Worker ID + Sequence Counter.",
     "Centralized database auto-increment sequence.",
     "Decentralized Snowflake generator running locally in app memory.",
     "NTP clock skew causes duplicate IDs across generation nodes.",
     "Requires clock drift detection and worker ID coordination."),

    (16, "16-database-indexes-in-system-design", "Database Indexes in System Design",
     "B-Tree and Hash indexes: accelerating queries at the cost of write amplification.",
     "Indexes speed up read lookups from O(N) to O(log N) while burdening every INSERT/UPDATE.",
     "Querying unindexed foreign key column.",
     "Composite B-Tree index matching query filter and sorting order.",
     "Full table scan triggers shared lock escalation under high concurrency.",
     "Every secondary index adds disk storage and slows down write throughput."),

    (17, "17-read-scaling", "Read Scaling Strategies",
     "Relational database reads exhaust single-node disk IOPS and connection pools.",
     "Distributing reads across asynchronous read replicas or in-memory caches.",
     "All reads and writes directed to primary database node.",
     "Primary handles writes; read replicas handle read traffic.",
     "High read concurrency starves write transactions of connection slots.",
     "Replicas introduce replication lag and eventual consistency anomalies."),

    (18, "18-replication-from-first-principles", "Replication From First Principles",
     "Primary-to-replica state copying: asynchronous vs synchronous log replication.",
     "State machine replication: shipping transaction logs vs statement-based replication.",
     "Single database node.",
     "Primary shipping write-ahead log (WAL) to asynchronous replicas.",
     "Primary crashes before WAL buffer is transmitted to replica (data loss window).",
     "Synchronous replication guarantees durability at the cost of write latency."),

    (19, "19-replication-lag", "Replication Lag",
     "Network and disk processing delays causing replica data to lag behind primary.",
     "Asynchronous replication implies eventual consistency; replica reads may be stale.",
     "Clients reading immediately from read replica.",
     "Monitor replication lag in milliseconds; route lag-sensitive reads to primary.",
     "User updates profile, refreshes page, and sees old data.",
     "Routing reads to primary reduces read replica offloading effectiveness."),

    (20, "20-read-after-write", "Read-After-Write Consistency",
     "Ensuring users always see their own updates immediately upon subsequent page reload.",
     "Read-Your-Writes consistency: routing a user's reads to primary within a TTL window.",
     "All user reads routed round-robin to replicas.",
     "Session-sticky routing to primary for 5 seconds following any write.",
     "User writes new comment, page reloads from replica, comment is missing.",
     "Increases read load on primary database during high user engagement."),

    (21, "21-consistency-models", "Consistency Models",
     "Linearizable, Sequential, Causal, Read-Your-Writes, and Eventual Consistency.",
     "Consistency describes the observable ordering and freshness of reads relative to writes.",
     "Assuming all database nodes are instantly synchronized.",
     "Explicitly defining consistency boundaries per domain use case.",
     "Concurrent updates produce conflicting state on divergent nodes.",
     "Stronger consistency models require network round-trips and reduce write throughput."),

    (22, "22-cap-from-first-principles", "CAP Theorem From First Principles",
     "Proving why a distributed system must choose between Availability and Consistency during partitions.",
     "In the presence of a network partition, nodes cannot synchronize state synchronously.",
     "Two nodes accepting writes without cross-network communication.",
     "Choose CP (reject writes on minority partition) or AP (accept writes with divergence).",
     "Network partition isolates Node A and Node B; both accept conflicting balance debits.",
     "AP systems require conflict resolution; CP systems experience downtime during partitions."),

    (23, "23-pacelc-intuition", "PACELC Intuition",
     "Extending CAP: When there is no partition, evaluating Latency vs Consistency tradeoffs.",
     "If Partition (P) choose A or C; Else (E) choose Latency (L) or Consistency (C).",
     "Assuming systems only trade off during network failures.",
     "Configuring replication ACK policies: ACK on 1 node (low latency) vs ACK on all (strong consistency).",
     "Synchronous write across 3 datacenters causes 150ms p99 latency.",
     "Low latency writes risk data loss if primary node crashes before replica ACK."),

    (24, "24-database-failover", "Database Failover",
     "Promoting a read replica to primary when the primary host crashes.",
     "Heartbeat detection, consensus-based promotion, and client connection re-routing.",
     "Manual operator intervention upon primary crash.",
     "Automated failover coordinator (Patroni / Orchestrator / Raft).",
     "Old primary recovers after failover and accepts writes (Split-Brain).",
     "Automated failover carries false-positive risks during transient network blips."),

    (25, "25-caching-from-first-principles", "Caching From First Principles",
     "Sub-millisecond memory lookups shielding slow disk and database queries.",
     "Locality of reference: 80% of reads target 20% of the dataset.",
     "Every read hits the primary relational database.",
     "In-memory key-value cache layer (Redis/Memcached).",
     "Database CPU reaches 100% under identical repeated product queries.",
     "Cache introduces memory cost, cache invalidation bugs, and data staleness."),

    (26, "26-cache-aside", "Cache-Aside Pattern",
     "Application queries cache first; on miss, fetches from database and populates cache.",
     "Lazy loading ensures only actively accessed keys consume cache memory.",
     "Application directly queries database.",
     "Cache-Aside pattern with explicit expiration TTL.",
     "Cache miss penalty under unprimed cold cache start.",
     "First request experiences high latency (cache miss + DB seek + cache write)."),

    (27, "27-cache-invalidation", "Cache Invalidation",
     "Keeping cached values synchronized with updates in the underlying database.",
     "There are only two hard things in Computer Science: cache invalidation and naming things.",
     "Relying solely on long TTLs for cache freshness.",
     "Write-through or explicit invalidation upon database update commit.",
     "Database updated, cache retaining stale price for 1 hour.",
     "Race condition: concurrent read populates cache with stale data during write invalidation."),

    (28, "28-cache-eviction", "Cache Eviction Policies",
     "Managing finite cache memory using LRU, LFU, FIFO, and Random eviction.",
     "Eviction algorithms trade hit ratio optimization for algorithmic complexity.",
     "Unbounded in-memory dictionary causing process OOM.",
     "Least Recently Used (LRU) eviction with linked hash map.",
     "Scanning large unindexed batch flushes all hot keys out of LRU cache.",
     "LRU requires updating doubly-linked list pointers on every single read hit."),

    (29, "29-cache-stampede", "Cache Stampede / Thundering Herd",
     "Hot key expires; hundreds of concurrent requests miss simultaneously and crash the DB.",
     "Probabilistic early expiration (XFetch) or mutex locking prevents parallel re-computation.",
     "Naive Cache-Aside without concurrency locking.",
     "Mutex locking (single-flight) allowing only one thread to regenerate expired cache key.",
     "Cache key expires under 5,000 QPS; 5,000 queries hit DB simultaneously.",
     "Mutex locking forces concurrent readers to wait until single-flight reload finishes."),

    (30, "30-hot-keys", "Hot Keys in Distributed Caches",
     "A single popular celebrity profile saturates a single cache node's network bandwidth.",
     "Hash-based cache partitioning assigns identical keys to the exact same node.",
     "Single Redis key for celebrity account receiving 100,000 QPS.",
     "Local in-process L1 cache or key splitting (`celebrity_id#1`, `celebrity_id#2`).",
     "Single Redis cluster node hits 100% CPU while other nodes are idle.",
     "Key splitting complicates cache invalidation across all split keys."),

    (31, "31-cdn-from-first-principles", "CDN From First Principles",
     "Edge caching static media and cached API responses geographically close to users.",
     "Speed of light in fiber optics limits cross-continent latency to ~100ms+ RTT.",
     "All global users fetch static images from single origin datacenter.",
     "Global Content Delivery Network (CDN) with Points of Presence (PoPs).",
     "Global users in Europe experience 250ms latency fetching images from US origin.",
     "Origin shielding, cache purge delays, and egress bandwidth costs."),

    (32, "32-async-processing", "Asynchronous Processing",
     "Decoupling slow tasks (image processing, email dispatch) from the synchronous HTTP thread.",
     "Fast acknowledgement of requests; offloading heavy computation to background workers.",
     "HTTP handler sends confirmation email synchronously before returning HTTP 200.",
     "HTTP handler enqueues task to message broker and returns HTTP 202 Accepted immediately.",
     "External email provider hangs for 10 seconds; client connection times out.",
     "Client must poll or use WebSockets/webhooks to receive eventual task results."),

    (33, "33-queue-from-first-principles", "Queues From First Principles",
     "Producer-consumer architecture: buffers, durable storage, and worker pools.",
     "Queues smooth traffic spikes and protect downstream systems from overload.",
     "In-memory Python list queue.",
     "Durable disk-backed message queue (RabbitMQ / Redis Streams / SQS).",
     "Worker process crashes mid-task; task is lost forever from in-memory queue.",
     "Durable queueing adds disk write overhead and network hops."),

    (34, "34-queue-semantics", "Queue Semantics & Visibility",
     "Message leasing, visibility timeouts, acknowledgement (ACK), and dead-letter routing.",
     "A message must remain invisible to other workers while being processed.",
     "Queue deletes message immediately upon delivery to worker.",
     "Visibility timeout: worker must ACK upon completion; unacked messages re-appear.",
     "Worker crashes while processing; unacknowledged message is lost.",
     "If task takes longer than visibility timeout, duplicate processing occurs."),

    (35, "35-at-least-once-processing", "At-Least-Once Processing",
     "Network partitions and worker crashes make exactly-once physical delivery impossible.",
     "At-least-once delivery requires downstream consumers to be idempotent.",
     "Assuming every message will be delivered and processed exactly once.",
     "Embracing at-least-once delivery and building deduplication logic into workers.",
     "Network times out during ACK packet; broker redelivers message, charging card twice.",
     "Requires persistent deduplication storage and distributed locking."),

    (36, "36-idempotency", "Idempotency in Distributed Systems",
     "Designing operations that produce identical results when executed multiple times.",
     "Idempotency keys allow safe client retries without fear of duplicate state mutation.",
     "Non-idempotent `POST /payments` incrementing balance on every invocation.",
     "Idempotent `POST /payments` with `Idempotency-Key` header verified against DB store.",
     "Client retries payment on network timeout; customer is double-charged.",
     "Idempotency stores consume memory and require transaction cleanup TTLs."),

    (37, "37-retry", "Retries & Fault Classification",
     "Classifying errors into transient (retryable) vs permanent (non-retryable).",
     "Retrying a 400 Bad Request wastes compute; retrying a 503 Service Unavailable recovers.",
     "Blindly retrying all failed requests.",
     "Granular exception classification: retry on 503/504 and connection errors only.",
     "Retrying non-retryable 404/422 requests floods logs and wastes resources.",
     "Excessive retries amplify outages on degraded downstream services."),

    (38, "38-backoff-and-jitter", "Backoff and Jitter",
     "Preventing synchronized retry storms using exponential backoff with full randomization.",
     "Full Jitter decorrelates client retry attempts across the time domain.",
     "Fixed 1-second retry loop across all clients.",
     "Exponential backoff with Full Jitter: $sleep = random(0, min(cap, base \times 2^i))$.",
     "Downstream recovers; 10,000 clients retry at exact same millisecond, crashing it again.",
     "Adds randomized delay to client request completion."),

    (39, "39-dead-letter-queue", "Dead-Letter Queue (DLQ)",
     "Isolating unparseable poison pill messages into dedicated operational queues.",
     "A poison pill message must not cause infinite worker crash loops.",
     "Queue retries failing message infinitely.",
     "Route to Dead-Letter Queue after 3 failed delivery attempts with alert emission.",
     "Malformed JSON payload crashes worker process; message redelivered in infinite loop.",
     "DLQs require operational monitoring, alerting, and manual replay tooling."),

    (40, "40-event-driven-architecture", "Event-Driven Architecture",
     "Decoupling systems through state-change notifications rather than direct RPC calls.",
     "Events describe things that have already happened; producers do not care who listens.",
     "Order service directly invokes email, inventory, and analytics via synchronous HTTP.",
     "Order service emits `OrderPlaced` event; multiple consumers react independently.",
     "Email service outage blocks order checkout completion.",
     "Loss of global transaction visibility and complex eventual consistency debugging."),

    (41, "41-pub-sub", "Publish-Subscribe Pattern",
     "1-to-N message broadcast delivering events to multiple independent consumer groups.",
     "Decouples event publishers from consumer scaling and deployment lifecycles.",
     "Direct point-to-point queues between services.",
     "Topic-based Pub/Sub broker (SNS, Kafka, RabbitMQ Fanout).",
     "Adding a new analytics listener requires modifying producer code.",
     "High consumer fan-out increases broker network egress and CPU utilization."),

    (42, "42-event-log", "Append-Only Event Logs",
     "Ordered, immutable, replayable stream storage partitioned across cluster nodes.",
     "An event log is a durable source of truth; consumers track individual offsets.",
     "Ephemeral message queues that delete messages immediately upon consumption.",
     "Partitioned append-only commit log (Apache Kafka architecture).",
     "New analytics service needs historical data from past 30 days but queue deleted it.",
     "Requires managing disk retention policies and partition consumer rebalances."),

    (43, "43-queue-vs-log", "Queue vs Log Architectural Decision",
     "Choosing between task distribution queues (RabbitMQ/SQS) and event streams (Kafka).",
     "Queues distribute independent work units; logs preserve strict ordering and replayability.",
     "Using Kafka as a simple background task queue.",
     "RabbitMQ for complex routing and task queues; Kafka for event streaming and replay.",
     "Kafka partition head-of-line blocking stalls unrelated messages when one message fails.",
     "Running both systems increases infrastructure complexity."),

    (44, "44-consumer-lag", "Consumer Lag",
     "Measuring the deficit between producer write offset and consumer read offset.",
     "Consumer lag indicates whether worker capacity is sufficient to sustain ingestion.",
     "Unmonitored background consumers.",
     "Track consumer lag metric in Prometheus; auto-scale consumer workers on lag spikes.",
     "Traffic surge creates 2-hour event backlog; downstream analytics reports stale data.",
     "Scaling consumers is limited by the number of partitions in the event stream."),

    (45, "45-backpressure", "Backpressure From First Principles",
     "Signaling upstream producers to throttle when downstream consumers are saturated.",
     "Buffering absorbs transient bursts; backpressure prevents catastrophic memory failure.",
     "Unbounded producer pushing events into memory until heap crashes.",
     "Reactive backpressure with high/low watermarks and HTTP 429 pushback.",
     "Downstream database slow; upstream server keeps accepting requests and OOMs.",
     "Upstream clients must handle rate limiting and delay retries."),

    (46, "46-partitioning-data", "Partitioning Data",
     "Distributing database datasets across multiple physical machines.",
     "Horizontal sharding overcomes single-server storage and write throughput ceilings.",
     "Single monolithic database table holding 1 billion rows.",
     "Sharding rows across $N$ database nodes using hash partitioning: $hash(key) \% N$.",
     "Single database disk hits 100% capacity; write IOPS maxed out.",
     "Cross-shard queries and joins become distributed and expensive."),

    (47, "47-partitioning-problems", "Partitioning Pitfalls & Node Additions",
     "The catastrophic key remapping that occurs when adding node $N+1$ to modulo partitioning.",
     "Modulo hashing ($key \% N$) invalidates almost all key locations when $N$ changes.",
     "Simple modulo sharding ($hash(key) \% 3$).",
     "Adding 4th node causes 75% of all keys to move, triggering cache wipeout.",
     "Cluster expansion causes severe database migration storm and cache misses.",
     "Demonstrates why consistent hashing is mandatory for dynamic clusters."),

    (48, "48-consistent-hashing", "Consistent Hashing",
     "Minimizing key movement when scaling nodes using a circular hash ring with virtual nodes.",
     "Consistent hashing guarantees that adding or removing a node moves only $K/N$ keys.",
     "Naive modulo sharding.",
     "Consistent hash ring with 100 virtual nodes per physical server.",
     "Adding a node moves almost all keys and causes severe cache cold-starts.",
     "Virtual nodes increase ring traversal complexity and memory overhead."),

    (49, "49-hash-slots", "Hash Slots Partitioning",
     "Deterministic pre-allocated slot architectures (Redis Cluster model).",
     "Fixed 16,384 hash slots simplify cluster rebalancing and partition mapping.",
     "Dynamic key-range boundaries requiring complex rebalancing coordination.",
     "Deterministic slot mapping ($CRC16(key) \% 16384$) with slot migration tracking.",
     "Cluster node failure leaves keys in unassigned slot ranges.",
     "Multi-key operations must belong to the same hash slot (using hash tags `{...}`)."),

    (50, "50-range-partitioning", "Range Partitioning",
     "Partitioning data by contiguous alphanumeric or timestamp ranges.",
     "Range partitioning enables efficient range scans (`BETWEEN A AND B`).",
     "Hash partitioning making range scans fan out to every single shard.",
     "Range partitioning with dynamic split thresholds (Bigtable / HBase model).",
     "Monotonically increasing timestamp keys send 100% of all writes to the latest shard.",
     "Write hotspotting on the latest partition requires periodic automated splitting."),

    (51, "51-shard-key-selection", "Shard Key Selection",
     "Selecting high-cardinality, evenly distributed partition keys to avoid hot spots.",
     "A bad shard key creates skewed hot partitions that degrade the entire cluster.",
     "Sharding by `country_code` where 80% of users reside in one country.",
     "Compound shard key (`tenant_id + user_id`) guaranteeing uniform distribution.",
     "Hot partition crashes under localized load while other shards are 95% idle.",
     "Queries that omit the shard key must fan out to all cluster partitions."),

    (52, "52-cross-shard-queries", "Cross-Shard Queries & Fan-Out",
     "The latency and resource overhead of querying across multiple distributed shards.",
     "Scatter-gather queries take as long as the slowest responding shard.",
     "Querying by secondary attribute across 50 sharded database nodes.",
     "Global secondary index (GSI) or denormalized read-side lookup table.",
     "Single user search query fans out to 50 shards, exhausting connection pools.",
     "Global secondary indexes require asynchronous replication and eventual consistency."),

    (53, "53-rebalancing", "Partition Rebalancing",
     "Moving partition data across physical nodes online without cluster downtime.",
     "Live migration requires dual-writing, background replication, and atomic cutover.",
     "Taking database offline to re-partition and copy data.",
     "Online partition rebalancing with change capture and routing table propagation.",
     "Data divergence between source and target shards during live migration.",
     "Rebalancing consumes network and disk I/O, temporarily degrading query latency."),

    (54, "54-replication-plus-partitioning", "Replication + Partitioning Topology",
     "Combining horizontal sharding for scale with primary-replica replication for HA.",
     "Each shard is internally replicated across multiple Availability Zones.",
     "Single non-replicated primary per shard.",
     "Sharded cluster where each shard has 1 primary and 2 read replicas.",
     "Shard 2 primary hardware failure brings down 25% of all user accounts.",
     "Significantly increases server counts, network topology, and operational management."),

    (55, "55-quorums", "Quorum Replicated State",
     "Configuring $N, W, R$ parameters to tune consistency vs availability.",
     "Strict quorum overlap ($W + R > N$) guarantees that read quorum overlaps write quorum.",
     "Writing to 1 node, reading from 1 node ($W=1, R=1, N=3$).",
     "Quorum configuration: $N=3, W=2, R=2$ ($2 + 2 > 3$).",
     "Reading stale data from lagging replica under $W=1, R=1$.",
     "Quorum reads and writes require coordinating multiple network roundtrips."),

    (56, "56-leader-based-replication", "Leader-Based Replication",
     "Single leader coordinating all cluster writes; followers streaming replication logs.",
     "Single-leader guarantees deterministic write ordering at the cost of write scalability.",
     "Multi-leader writes causing immediate data conflicts.",
     "Raft/Paxos leader coordination with automated heartbeat failover.",
     "Leader dies; cluster enters read-only election window.",
     "All write throughput is bottlenecked by the single leader node's capacity."),

    (57, "57-leaderless-replication", "Leaderless Replication",
     "Dynamo-style architectures accepting writes and reads on any cluster replica.",
     "Leaderless architectures maximize write availability during network splits.",
     "Strict leader routing failing when leader is partitioned.",
     "Leaderless writes to $W$ replicas with Read Repair and Hinted Handoff.",
     "Concurrent writes to different replicas create conflicting versions.",
     "Requires conflict resolution mechanisms and higher read latency for quorum checks."),

    (58, "58-conflict-resolution", "Conflict Resolution: LWW vs CRDTs",
     "Resolving concurrent divergent writes: Last-Write-Wins vs Conflict-Free Replicated Data Types.",
     "LWW silently drops data due to clock skew; CRDTs mathematically converge without loss.",
     "Last-Write-Wins based on physical wall-clock timestamps.",
     "State-based and operation-based CRDTs (e.g. PN-Counter, OR-Set).",
     "Two concurrent cart additions resolve via LWW; one item disappears silently.",
     "CRDTs require specialized data structures and additional metadata storage."),

    (59, "59-time-in-distributed-systems", "Time in Distributed Systems",
     "Physical clock drift, NTP limits, and why wall clocks cannot establish total ordering.",
     "Network packet delay is unbounded; physical clocks across machines always drift.",
     "Using `time.time()` to determine the order of distributed events.",
     "Monotonic clocks for intervals; logical clocks for distributed causal ordering.",
     "NTP synchronization step causes server clock to jump backward 200ms.",
     "Physical clocks cannot guarantee total global order across independent servers."),

    (60, "60-logical-clocks", "Lamport Logical Clocks",
     "Establishing partial ordering of events in distributed systems without physical clocks.",
     "Happened-Before relation ($\to$): $L(e) < L(e')$ for causally related events.",
     "Relying on timestamps to order distributed chat messages.",
     "Lamport process clock incrementing on local events and updating on message receipt.",
     "Message appears sent before it was received due to client clock drift.",
     "Lamport clocks cannot determine whether two events were causally concurrent."),

    (61, "61-vector-clocks-concept", "Vector Clocks",
     "Detecting concurrent conflicting updates across multi-master distributed nodes.",
     "An array of logical clocks tracks causal history across all participant nodes.",
     "Single integer Lamport clock.",
     "Vector clock assigning version vectors to detect concurrent conflicting writes.",
     "Two nodes update the same key independently; system cannot detect conflict.",
     "Vector clock size grows linearly with the number of cluster writer nodes."),

    (62, "62-coordination-problem", "The Coordination Problem",
     "Electing leaders, allocating resource locks, and managing shard ownership.",
     "Without coordination, distributed systems risk split-brain and conflicting actions.",
     "Each server independently decides who performs background cron jobs.",
     "Centralized distributed coordination service (ZooKeeper / Consul / etcd).",
     "Two workers execute the exact same scheduled billing job simultaneously.",
     "The coordinator service becomes a critical dependency and availability bottleneck."),

    (63, "63-leader-election", "Leader Election Algorithms",
     "Bully algorithm and heartbeat leasing protocols for cluster leadership.",
     "Nodes with highest rank or earliest lease acquire authoritative cluster leadership.",
     "Manual leader promotion upon node crash.",
     "Bully election protocol: nodes challenge higher IDs; highest active node claims leader.",
     "Transient network split causes two nodes to both declare themselves leader.",
     "Requires odd-numbered quorums to prevent split-brain leadership elections."),

    (64, "64-consensus-problem", "The Consensus Problem",
     "Reaching agreement on authoritative state among untrusted network nodes under failure.",
     "FLP Impossibility theorem: deterministic consensus is impossible in async networks with 1 unannounced crash.",
     "Assuming simple majority votes guarantee consensus in async networks.",
     "Consensus state machine replication (Paxos / Raft).",
     "Network delay causes nodes to perpetually restart elections (split vote livelock).",
     "Consensus algorithms sacrifice write latency for mathematical correctness."),

    (65, "65-raft-mental-model", "Raft Consensus Mental Model",
     "Leader election, log replication, terms, and majority commit guarantees.",
     "A log entry is committed only when replicated on a majority of cluster nodes in current term.",
     "Ad-hoc replication scripts.",
     "Raft state machine: Follower -> Candidate -> Leader with randomized election timers.",
     "Partitioned old leader attempts to commit stale log entries.",
     "Raft requires $2f + 1$ nodes to tolerate $f$ node failures."),

    (66, "66-consensus-vs-replication", "Consensus vs Replication",
     "Differentiating copying data from reaching consensus on authoritative commit order.",
     "Replication copies data; consensus guarantees all nodes agree on identical state transitions.",
     "Confusing primary-replica asynchronous replication with consensus.",
     "Using consensus (etcd/Raft) for critical metadata; async replication for bulk data.",
     "Asynchronous replica promoted to leader loses committed transactions.",
     "Consensus is too slow and compute-heavy for high-volume petabyte-scale data."),

    (67, "67-distributed-locks", "Distributed Locks From First Principles",
     "Mutual exclusion across multiple servers using Redis / ZooKeeper leases.",
     "A lock is a lease with an explicit TTL to prevent deadlocks on worker death.",
     "Local in-memory threading.Lock() on multi-instance cluster.",
     "Distributed lock with unique ownership UUID and atomic release script.",
     "Worker crashes while holding lock; resource remains blocked forever.",
     "GC pauses and network stalls can cause lock lease to expire while worker is still writing."),

    (68, "68-fencing-tokens", "Fencing Tokens",
     "Preventing zombie workers from corrupting storage after lock lease expiration.",
     "A monotonically increasing fencing token rejects write requests from expired lock holders.",
     "Naive distributed lock without fencing tokens.",
     "Storage layer checks: `UPDATE resource SET data = ? WHERE token > last_token`.",
     "Worker A pauses for 10s (GC pause); lock expires; Worker B acquires lock; Worker A writes stale data.",
     "Requires downstream storage engine to support conditional version checks."),

    (69, "69-transactions-across-services", "Transactions Across Services",
     "The dual-write defect: database update succeeds, but message broker publish fails.",
     "Local ACID transactions cannot cross network boundaries without distributed coordination.",
     "Service writes to PostgreSQL and then immediately sends message to Kafka.",
     "Transactional Outbox pattern committing event to local DB table.",
     "Database commits order, but network dies before Kafka publish; inventory never decrements.",
     "Distributed transactions reduce availability and increase latency."),

    (70, "70-two-phase-commit-concept", "Two-Phase Commit (2PC)",
     "Prepare and Commit phases coordinating atomic distributed transactions.",
     "Coordinator asks participants to prepare; commits only if all vote YES.",
     "Independent uncoordinated microservice writes.",
     "Two-Phase Commit protocol with transaction coordinator.",
     "Coordinator crashes after Prepare phase; all participant resources remain locked.",
     "2PC is a blocking protocol; failure of coordinator halts all participant resources."),

    (71, "71-saga-pattern", "Saga Pattern",
     "Managing distributed transactions using a sequence of local transactions and compensations.",
     "Compensating transactions undo previous steps if a downstream step fails.",
     "Attempting distributed ACID transactions across microservices.",
     "Saga workflow: Reserve Inventory -> Charge Card -> Ship Order (with compensating refunds).",
     "Payment fails after inventory is reserved; inventory remains locked without compensation.",
     "Compensating transactions are not traditional rollbacks; intermediate states are visible to users."),

    (72, "72-orchestration-vs-choreography", "Orchestration vs Choreography",
     "Centralized workflow coordinators vs decentralized event-driven reactions.",
     "Orchestration centralizes logic and visibility; choreography provides loose coupling.",
     "Complex choreography where tracing workflow state requires analyzing 10 event queues.",
     "Centralized Saga Orchestrator maintaining explicit state machine and executing step calls.",
     "Event storm in choreographed system causes circular event loops.",
     "Orchestrator becomes a central point of architectural coupling."),

    (73, "73-transactional-outbox", "Transactional Outbox Pattern",
     "Writing domain state and outbox events in a single atomic database transaction.",
     "Guarantees that an event is published if and only if the database transaction commits.",
     "Direct network calls to Kafka inside HTTP request handler.",
     "Local outbox table polled by asynchronous publisher process.",
     "Service crashes after DB commit but before message publish; event is lost.",
     "Requires an outbox polling worker or CDC log reader and deduplication handling."),

    (74, "74-change-data-capture", "Change Data Capture (CDC)",
     "Streaming database row mutations directly from the Write-Ahead Log (WAL) to event brokers.",
     "CDC decouples downstream event consumers without polling overhead or table locks.",
     "Periodic SQL polling (`SELECT * FROM outbox WHERE status = 'PENDING'`).",
     "CDC engine (Debezium) streaming PostgreSQL WAL directly to Kafka.",
     "Outbox polling table query causes lock contention on high-volume database.",
     "Requires database WAL replication permissions and schema evolution coordination."),

    (75, "75-search-systems", "Search Systems & Inverted Indexes",
     "Why relational B-Trees fail for full-text search, relevance ranking, and fuzzy matching.",
     "Inverted indexes map terms to posting lists of document IDs for sub-millisecond retrieval.",
     "SQL `LIKE '%term%'` full table scans across millions of text records.",
     "Inverted index engine (Elasticsearch / OpenSearch).",
     "Database CPU hits 100% running wild-card text scans under concurrent user search.",
     "Search indexes are derived state and require synchronization pipelines from primary DB."),

    (76, "76-search-index-as-derived-state", "Search Index as Derived State",
     "Treating search clusters as secondary derived views rebuildable from the primary DB.",
     "The primary database is the single source of truth; search index is an ephemeral projection.",
     "Using Elasticsearch as the primary authoritative store for e-commerce orders.",
     "PostgreSQL primary with asynchronous CDC updating Elasticsearch.",
     "Elasticsearch cluster corruption causes irreversible loss of customer orders.",
     "Eventual consistency: there is a short replication delay before new items appear in search."),

    (77, "77-object-storage", "Object Storage From First Principles",
     "Storing unstructured binary blobs (images, videos, backups) vs relational databases.",
     "Object stores provide practically infinite scalability and high durability (11 nines).",
     "Storing 10 MB user images as BLOBs inside PostgreSQL tables.",
     "S3-compatible Object Storage storing raw bytes, returning immutable HTTP URLs.",
     "Database backup size and memory explode due to heavy binary BLOB storage.",
     "Object storage does not support partial in-place byte modifications; objects are immutable."),

    (78, "78-metadata-vs-blob-storage", "Metadata vs Blob Storage Separation",
     "Storing structured file attributes in relational DB and binary bytes in object store.",
     "Separation of concerns: fast structured SQL queries on metadata, scalable blob retrieval.",
     "Storing file metadata and bytes inside the same storage engine.",
     "Relational DB: `(file_id, user_id, size, s3_key, created_at)` + S3: `s3://bucket/s3_key`.",
     "Querying user file list requires scanning massive disk pages containing image bytes.",
     "Requires garbage collection to delete orphaned S3 blobs if metadata write fails."),

    (79, "79-content-delivery", "Content Delivery Architecture",
     "Accelerating media delivery via CDN edge caches, origin shielding, and pre-signed URLs.",
     "Pre-signed URLs allow clients to upload/download directly to object storage without server proxying.",
     "Clients upload large video files through application server process memory.",
     "API generates pre-signed S3 upload URL; client uploads directly to object storage.",
     "App server thread pool exhausted proxying 500 MB video uploads.",
     "Requires client-side upload progress handling and asynchronous transcode webhooks."),

    (80, "80-rate-limiting", "Rate Limiting Algorithms",
     "Protecting APIs from abuse using Token Bucket, Leaky Bucket, and Sliding Window.",
     "Rate limiting prevents resource starvation and protects downstream infrastructure.",
     "Unrestricted API accepting unbounded requests from single IP address.",
     "Token Bucket rate limiter allowing controlled burstiness with constant refill rate.",
     "Rogue script spams login endpoint, taking down backend authentication server.",
     "Rejects legitimate users during sudden burst traffic if capacity is tuned too strictly."),

    (81, "81-distributed-rate-limiting", "Distributed Rate Limiting",
     "Coordinating rate limits across multiple stateless application instances using Redis.",
     "Local in-memory counters diverge across instances, allowing clients to bypass limits.",
     "Local in-memory rate limiting counters on each app server.",
     "Centralized Redis sliding window counter evaluated via atomic Lua scripts.",
     "Client bypasses rate limits by round-robining requests across 10 app servers.",
     "Redis roundtrip latency adds 1-2ms to every incoming HTTP request."),

    (82, "82-load-shedding", "Load Shedding & Graceful Overload",
     "Rejecting lower-priority traffic when server CPU or concurrency exceeds safe thresholds.",
     "Better to serve 80% of traffic successfully than let 100% of requests timeout and fail.",
     "Server attempts to process all incoming requests, enters swap, and crashes.",
     "Load shedding middleware returning HTTP 503 / 429 when queue depth > threshold.",
     "Incoming surge causes request backlog, exhausting file descriptors and killing process.",
     "Clients experience fast-fail rejections during peak surge traffic."),

    (83, "83-circuit-breakers", "Circuit Breakers",
     "Preventing cascading failures by fast-failing calls to degraded downstream services.",
     "CLOSED -> OPEN -> HALF_OPEN state machine isolates dependency outages.",
     "Service A blocks for 30s waiting on unresponsive Service B until thread pool dies.",
     "Circuit breaker tripping to OPEN after 5 consecutive failures, fast-failing for 30s.",
     "Downstream service outage causes upstream service thread exhaustion and cascade failure.",
     "Users receive immediate fallback errors instead of delayed responses."),

    (84, "84-bulkheads", "Bulkheads",
     "Isolating resource pools (threads, connections, memory) between independent workloads.",
     "Failure in one non-critical dependency must not starve critical path resources.",
     "Single shared thread pool serving both checkout requests and analytics queries.",
     "Separate isolated thread pools / connection pools for Checkout vs Analytics.",
     "Slow analytics query consumes all 100 DB connections, halting checkout orders.",
     "Static resource partitioning may lead to lower overall resource utilization."),

    (85, "85-timeout-budgets", "Timeout Budgets & Deadlines",
     "Allocating and propagating request deadlines across distributed microservice call graphs.",
     "If an end-to-end request budget is 500ms, downstream services must share the remaining time.",
     "Each microservice hop configures an independent 5-second timeout.",
     "Deadline propagation: passing remaining time budget in HTTP headers (`grpc-timeout`).",
     "Client cancels request after 500ms, but downstream services continue heavy processing.",
     "Requires clock synchronization and uniform deadline propagation across all RPC clients."),

    (86, "86-retry-amplification", "Retry Amplification",
     "The geometric explosion of requests caused by multi-tier retries during partial outages.",
     "If 4 service layers each retry 3 times, a single failed call generates $3^3 = 27$ requests.",
     "Every microservice retries failed downstream calls 3 times.",
     "Retry budgets: limit retries to maximum 10% of total traffic; retry only at edge gateway.",
     "Transient network glitch causes 27x retry burst, knocking downstream service completely offline.",
     "Failing fast without retry may slightly decrease single-request success rate."),

    (87, "87-graceful-degradation", "Graceful Degradation",
     "Serving degraded or cached responses when optional dependencies fail.",
     "Critical functionality (e.g. checkout) must survive failure of non-critical features (recommendations).",
     "E-commerce product page crashes entirely because recommendation service is down.",
     "Fallback handler returning static popular items if recommendation service fails.",
     "Non-critical service failure breaks core revenue-generating user flows.",
     "Users receive generic or slightly stale recommendations during degradation."),

    (88, "88-availability", "Availability & Calculating Nines",
     "Quantifying uptime percentages and annual downtime budgets.",
     "Availability = (Uptime / Total Time) * 100. 99.9% = 8.76 hrs downtime; 99.99% = 52.6 mins.",
     "Describing a system as 'highly available' without concrete numerical SLAs.",
     "Calculating availability budgets and configuring alerts based on error budget burn rate.",
     "Service outage exceeds monthly SLA threshold, triggering financial penalties.",
     "Higher availability requires exponential increases in redundancy, complexity, and cost."),

    (89, "89-reliability-vs-availability", "Reliability vs Availability",
     "Distinguishing whether a service is available from whether its responses are correct.",
     "A service returning HTTP 200 with corrupt or empty data is available, but completely unreliable.",
     "Monitoring only HTTP status codes (200 OK) without validating payload correctness.",
     "Semantic monitoring: asserting response validity and invariant correctness.",
     "Bug in pricing engine returns price $0.00 with HTTP 200 OK, costing millions.",
     "Semantic payload inspection adds small CPU overhead to telemetry pipelines."),

    (90, "90-fault-domains", "Fault Domains & Failure Isolation",
     "Isolating infrastructure across processes, physical servers, racks, AZs, and regions.",
     "A single physical fault (power loss, top-of-rack switch) must not kill all redundant nodes.",
     "Deploying all 3 primary-replica database nodes onto the same physical rack/host.",
     "Anti-affinity placement spreading instances across independent Availability Zones.",
     "Rack power supply failure takes down all replicas simultaneously.",
     "Cross-AZ network communication incurs slight latency and cloud data transfer costs."),

    (91, "91-redundancy", "Redundancy vs High Availability",
     "Why passive redundancy alone does not guarantee availability without automated failover.",
     "Redundancy provides spare capacity; availability requires detection, routing, and recovery.",
     "Maintaining cold standby database with no automated heartbeat or failover mechanism.",
     "Active-active redundancy with automated load balancing and health checks.",
     "Primary crashes; secondary sits idle while service remains down for 4 hours.",
     "Active-active redundancy requires conflict resolution and complex synchronization."),

    (92, "92-single-points-of-failure", "Single Points of Failure (SPOF)",
     "Auditing architecture diagrams to detect hidden, unmanaged single points of failure.",
     "Any component whose individual failure halts the entire system is an SPOF.",
     "Redundant app servers connected to a single un-replicated database or DNS provider.",
     "Comprehensive SPOF audit: multi-AZ database clustering, redundant load balancers.",
     "Single DNS provider encounters DDoS attack, taking down global application.",
     "Eliminating every SPOF increases architectural and financial investment."),

    (93, "93-multi-az-design", "Multi-AZ Design",
     "Deploying systems across multiple isolated Availability Zones within a single region.",
     "AZs provide distinct power, networking, and flood plains with sub-millisecond latency.",
     "Single-AZ deployment vulnerable to datacenter-wide power grid failure.",
     "Multi-AZ deployment with synchronous database replication across 3 AZs.",
     "Datacenter power outage takes down entire production system.",
     "Cross-AZ data transfer fees and sub-millisecond network latency overhead."),

    (94, "94-multi-region-motivations", "Multi-Region Motivations",
     "Justifying multi-region architecture: catastrophic disaster recovery, latency, and data sovereignty.",
     "Multi-region is expensive and complex; only justify it under concrete business requirements.",
     "Prematurely designing multi-region architecture for a small startup service.",
     "Single-region multi-AZ primary with warm standby in secondary region for disaster recovery.",
     "Entire cloud region suffers catastrophic fiber cut or outage.",
     "Massive increase in data transfer costs, replication lag, and operational burden."),

    (95, "95-multi-region-complexity", "Multi-Region Complexity",
     "The distributed pitfalls of multi-region: replication lag, conflicts, and split-brain.",
     "Speed of light enforces ~70ms+ roundtrip latency between continents.",
     "Assuming multi-region active-active databases behave like local databases.",
     "Active-Passive regional routing with asynchronous cross-region replication.",
     "Cross-region write conflicts overwrite data under active-active multi-region.",
     "Active-active requires complex conflict resolution or partitioned user routing."),

    (96, "96-disaster-recovery", "Disaster Recovery: RPO & RTO",
     "Defining Recovery Point Objective (data loss) and Recovery Time Objective (downtime).",
     "Business impact analysis defines the acceptable data loss window and downtime duration.",
     "Backing up database once per week with no recovery plan (RPO = 7 days).",
     "Continuous WAL archiving and point-in-time recovery (RPO < 5 mins, RTO < 30 mins).",
     "Ransomware attacks database; company loses 6 days of customer transactions.",
     "Lowering RPO/RTO requires continuous automated replication and regular DR fire drills."),

    (97, "97-backups", "Backups: Replication Is Not a Backup",
     "Why live replication does not protect against data corruption, ransomware, or DROP TABLE.",
     "A `DROP TABLE` command replicates to all read replicas within 50 milliseconds.",
     "Relying on read replicas as a backup strategy.",
     "Immutable, versioned, air-gapped point-in-time snapshots stored in separate accounts.",
     "Rogue employee executes `DROP TABLE`; all replicas instantly delete the table.",
     "Snapshot storage costs and operational overhead of periodic recovery testing."),

    (98, "98-capacity-planning", "Capacity Planning",
     "Deriving required CPU cores, RAM, and network bandwidth from projected traffic numbers.",
     "Capacity planning prevents surprise outages by matching infrastructure to growth curves.",
     "Guessing server sizes without quantitative mathematical derivation.",
     "Mathematical capacity model linking DAU, QPS, latency, and resource saturation.",
     "Traffic surges on marketing launch day; servers run out of memory and crash.",
     "Over-provisioning wastes money; under-provisioning causes system outages."),

    (99, "99-queue-capacity", "Queue Capacity & Sizing",
     "Calculating queue backlog growth, buffer sizing, and worker catch-up velocity.",
     "A queue must be sized to hold accumulated messages during worst-case consumer outages.",
     "Configuring small default queue buffer that overflows during worker restart.",
     "Queue sized for 4 hours of maximum peak write traffic with auto-scaling workers.",
     "Downstream worker crashes for 1 hour; queue fills up and drops incoming messages.",
     "Large queues consume disk storage and increase end-to-end message delivery latency."),

    (100, "100-connection-capacity", "Connection Capacity & Limits",
     "Managing socket file descriptors, epoll limits, and database connection pool sizes.",
     "Every open TCP connection consumes OS kernel memory and a file descriptor.",
     "Opening fresh database connection per incoming HTTP request.",
     "Bounded connection pools and connection proxies (e.g. PgBouncer).",
     "High concurrent traffic exhausts PostgreSQL connection limit, throwing 'Too many connections'.",
     "Connection pool queuing adds latency when all connections are checked out.")
]
