"""
Phase metadata definitions for Part 2 (Phases 101 to 200).
"""

PHASES_PART_2 = [
    (101, "101-storage-growth", "Storage Growth & Retention",
     "Projecting database and object store disk growth over 1, 3, and 5-year horizons.",
     "Storage capacity planning dictates partitioning schedules and archival strategies.",
     "Assuming storage needs remain constant.",
     "Automated tiering: active SSD storage, warm HDD storage, cold S3 glacier archive.",
     "Database disk fills to 100%, causing database crash and read-only lockdown.",
     "Data tiering adds retrieval latency for archived records."),

    (102, "102-cost-as-architecture-constraint", "Cost as an Architecture Constraint",
     "Evaluating the financial bills of compute, RAM, storage, and egress bandwidth.",
     "The best architecture is the simplest, most reliable design that fits the financial budget.",
     "Designing multi-datacenter active-active clusters for a $1,000/month project.",
     "Cost-optimized architecture balancing managed services with self-hosted instances.",
     "Cloud bill exceeds startup capital due to unmonitored egress bandwidth.",
     "Cost optimization may require accepting slightly higher operational maintenance."),

    (103, "103-security-in-system-design", "Security in System Design",
     "Defense-in-depth, zero-trust network boundaries, and principle of least privilege.",
     "Security is an architectural requirement, not an afterthought bolted on at deployment.",
     "Implicit trust between internal microservices over flat VPC network.",
     "Zero-trust mTLS service mesh with scoped cryptographic service identities.",
     "Attacker compromises single container and pivots across entire internal network.",
     "mTLS encryption adds CPU handshake overhead and certificate rotation operational complexity."),

    (104, "104-authentication-architecture", "Authentication Architecture",
     "Comparing centralized sessions, stateless JWT tokens, and identity providers.",
     "Stateless JWTs eliminate database lookups; centralized sessions allow instant revocation.",
     "Stateful session stored in central database queried on every API call.",
     "Stateless JWT access tokens with short TTL (15 mins) and sliding refresh tokens.",
     "Database CPU bottlenecks verifying session tokens under high API traffic.",
     "Stateless JWTs cannot be instantly revoked before expiration without a revocation blacklist."),

    (105, "105-authorization-architecture", "Authorization Architecture",
     "Role-Based Access Control (RBAC) vs Attribute-Based Access Control (ABAC).",
     "Authorization must be enforced at both the perimeter gateway and individual domain services.",
     "Hardcoded `if user.is_admin:` checks scattered across application code.",
     "Policy-as-code authorization engine (Open Policy Agent / centralized RBAC).",
     "IDOR vulnerability: user modifies URL ID to access another customer's invoice.",
     "Centralized policy checks introduce slight evaluation latency."),

    (106, "106-api-gateway-security-boundary", "API Gateway Security Boundary",
     "Perimeter security: TLS termination, rate limiting, WAF, and request sanitization.",
     "The gateway provides the first line of defense, shielding internal services from malicious payloads.",
     "Exposing internal microservices directly to the public internet.",
     "API Gateway enforcing TLS 1.3, DDoS protection, rate limits, and JWT authentication.",
     "Direct volumetric attack overwhelms internal services.",
     "API Gateway becomes a single point of failure if misconfigured."),

    (107, "107-observability-from-first-principles", "Observability From First Principles",
     "Why telemetry is mandatory: you cannot debug what you cannot observe.",
     "Observability allows operators to infer internal system state from external outputs (metrics, logs, traces).",
     "Guessing root cause of outages from user bug reports.",
     "Integrated observability pipeline: Prometheus metrics, structured logs, and OpenTelemetry traces.",
     "Outage occurs; logs are unformatted and lack correlation IDs, delaying recovery by hours.",
     "High-volume logging and tracing generate significant storage and network overhead."),

    (108, "108-metrics", "Metrics: Counters, Gauges, & Histograms",
     "Quantifying service traffic, error rates, and resource utilization.",
     "Metrics provide aggregated time-series data without per-event storage costs.",
     "Logging every request to text file and parsing with regex.",
     "Prometheus metric types: Counters (total requests), Gauges (active connections), Histograms (latency).",
     "High-cardinality labels (e.g. user_id as metric tag) explode metric database memory.",
     "Aggregated metrics lack individual request payload context."),

    (109, "109-distributed-tracing", "Distributed Tracing & Context Propagation",
     "Tracing user requests across complex asynchronous microservice topologies.",
     "Distributed traces connect parent and child spans via W3C `traceparent` headers.",
     "Debugging a 5-second latency spike across 8 microservices using isolated log files.",
     "Distributed tracing instrumented with OpenTelemetry and Jaeger.",
     "Cannot determine which downstream microservice caused a 3-second delay.",
     "Distributed trace collection adds small header parsing and network telemetry overhead."),

    (110, "110-correlation-ids", "Correlation IDs",
     "Passing a unique request identifier across HTTP calls, message queues, and async workers.",
     "A single correlation ID links all log lines generated by a single user transaction.",
     "Independent log files with unlinked log entries across 4 services.",
     "Correlation ID generated at gateway, propagated via HTTP headers and message payloads.",
     "Customer reports error 500; engineers cannot find the relevant log entries among millions.",
     "Requires strict engineering discipline to ensure all async workers propagate the ID."),

    (111, "111-sli-slo-concepts", "SLIs, SLOs, & Error Budgets",
     "Defining Service Level Indicators (measurements) and Service Level Objectives (targets).",
     "Error budgets quantify the acceptable rate of failure to balance innovation with reliability.",
     "Subjective debates over whether the system is 'fast enough'.",
     "SLO: 99.9% of requests succeed in < 200ms; automated alerts trigger on error budget burn rate.",
     "Deploying risky features during active outage exhausts remaining error budget.",
     "Strict SLOs may slow down deployment velocity if reliability is violated."),

    (112, "112-failure-detection", "Failure Detection in Asynchronous Networks",
     "Why perfect failure detectors are impossible in asynchronous networks.",
     "Cannot distinguish a slow node from a dead node or a partitioned network.",
     "Immediately declaring a node dead when a single ping times out.",
     "Phi Accrual failure detector evaluating sliding window of heartbeat arrival times.",
     "Premature failover: transient GC pause causes unnecessary primary failover and split-brain.",
     "Heartbeat detection introduces a detection delay window."),

    (113, "113-health-checks", "Health Checks: Liveness vs Readiness",
     "Shallow liveness (`/livez`) vs deep readiness (`/readyz`) dependency checking.",
     "Liveness asks: Is the process running? Readiness asks: Can it accept traffic right now?",
     "Single health check that queries database on every probe.",
     "Separating liveness (in-memory probe) from readiness (validates DB connection pool).",
     "Readiness probe failure causes Kubernetes to kill a healthy container during DB blip.",
     "Deep health checks that touch databases can overwhelm the database during mass restarts."),

    (114, "114-heartbeats", "Heartbeats & Lease Expirations",
     "Periodic pulse signals maintaining node health and distributed lock ownership.",
     "Heartbeat intervals must be balanced against lease timeouts to avoid false churn.",
     "Fixed 1-second lease with 1-second heartbeat interval.",
     "Lease timeout set to $3\times$ heartbeat interval with jitter.",
     "Transient network blip causes lease to expire prematurely while node is healthy.",
     "Frequent heartbeats consume network bandwidth in large clusters."),

    (115, "115-chaos-failure-injection", "Chaos Engineering & Failure Injection",
     "Proactively injecting failures into production-like environments to verify resilience.",
     "The best time to discover how a system fails is during business hours under controlled experiments.",
     "Waiting for natural outages to test failover procedures.",
     "Automated chaos tests injecting latency, dropping packets, and terminating random nodes.",
     "Failover script fails in production because it was never tested under real load.",
     "Chaos testing requires strict blast radius containment and automated rollback."),

    (116, "116-dependency-graphs", "Dependency Graphs & Blast Radius",
     "Mapping upstream and downstream service dependencies to isolate failure propagation.",
     "A service's availability can never exceed the product of its critical dependencies.",
     "Undocumented hidden microservice dependencies.",
     "Explicit dependency graph mapping critical path vs optional fallback services.",
     "Circular dependency between Service A and Service B causes mutual deadlock.",
     "Maintaining dependency graphs requires automated tracing and architecture governance."),

    (117, "117-critical-path", "Critical Path Latency Optimization",
     "Minimizing synchronous network hops on user-facing request paths.",
     "Every synchronous dependency on the critical path directly increases user-perceived latency.",
     "Sequentially invoking 6 microservices on the synchronous checkout path.",
     "Parallelizing independent RPC calls and moving non-critical operations to async queues.",
     "Single slow dependency adds 800ms directly to user checkout latency.",
     "Parallel execution increases concurrent connection usage on downstream systems."),

    (118, "118-fan-out", "Fan-Out Systems",
     "Querying $N$ distributed shards or services in parallel to assemble user responses.",
     "Fan-out maximizes parallel throughput but increases network contention and tail latency.",
     "Sequentially querying 20 database shards one by one.",
     "Parallel scatter-gather query with thread pool concurrency.",
     "One slow shard stalls the entire aggregated query response.",
     "High fan-out amplifies network packet bursts on the calling node."),

    (119, "119-tail-latency-amplification", "Tail Latency Amplification",
     "Why querying 100 services in parallel makes p99 latency govern 63% of user requests.",
     "Probability math: $P(\text{all succeed under p99}) = 0.99^{100} \approx 36.6\% \implies 63.4\%$ suffer p99.",
     "Assuming p99 tail latency only affects 1% of users in a distributed system.",
     "Hedged requests (sending duplicate request to replica if first takes > p95) and timeouts.",
     "User dashboard queries 100 microservices; over half of all users experience multi-second latency.",
     "Hedged requests consume additional compute and network capacity."),

    (120, "120-monolith-vs-microservices", "Monolith vs Microservices",
     "Evaluating architectural splits based on team boundaries, deployment velocity, and scale.",
     "Do not decompose a monolith until team communication or physical scaling forces it.",
     "Adopting microservices on Day 1 for a 3-person engineering team.",
     "Modular Monolith with strict package boundaries; extracting services only under pressure.",
     "Small team spends 70% of time debugging network boundaries and distributed deploys.",
     "Monoliths require disciplined modular boundary enforcement to avoid spaghetti code."),

    (121, "121-service-boundaries", "Domain Service Boundaries",
     "Decomposing systems by business capabilities and bounded contexts rather than technical layers.",
     "Services should encapsulate high internal cohesion and loose external coupling.",
     "Creating arbitrary microservices for every database table.",
     "Domain-Driven Design (DDD) bounded contexts: Orders, Catalog, Billing, Shipping.",
     "Frequent feature changes require synchronized deployments across 5 microservices.",
     "Defining bounded contexts requires deep domain understanding."),

    (122, "122-shared-database-problem", "The Shared Database Anti-Pattern",
     "Why multiple microservices reading and writing to the same database table creates coupling.",
     "Shared databases violate service encapsulation and create hidden lock dependencies.",
     "5 microservices sharing a single monolithic MySQL database schema.",
     "Database-Per-Service: each service owns its private datastore; communication via API/events.",
     "Service A alters a column type, breaking Service B in production.",
     "Database-per-service eliminates local ACID JOINs and cross-table foreign keys."),

    (123, "123-database-per-service", "Database Per Service Pattern",
     "Encapsulating data ownership inside each microservice boundary.",
     "Independent schema evolution, scaling, and technology choices per service domain.",
     "All services querying a single shared database.",
     "Orders Service owns PostgreSQL; Analytics owns ClickHouse; Users owns MongoDB.",
     "Cannot execute a SQL JOIN between Orders and Users tables.",
     "Requires distributed queries, data duplication, and eventual consistency pipelines."),

    (124, "124-sync-vs-async-service-communication", "Sync vs Async Communication",
     "Choosing between synchronous REST/gRPC and asynchronous message queues.",
     "Synchronous communication couples availability; asynchronous communication embraces eventual consistency.",
     "Using synchronous HTTP for all inter-service communication.",
     "Synchronous gRPC for immediate query reads; asynchronous Kafka events for state mutations.",
     "Service B downtime causes Service A to crash due to blocked HTTP connections.",
     "Async communication introduces message lag and complex tracing."),

    (125, "125-api-composition", "API Composition & BFF",
     "Aggregating data from multiple microservices into a unified client response.",
     "Backend-For-Frontend (BFF) tailors responses to specific client form factors (Mobile vs Web).",
     "Mobile client making 15 separate HTTP requests to assemble home screen.",
     "API Gateway / BFF aggregating downstream services in parallel and returning unified JSON.",
     "High mobile network latency and battery drain due to client-side scatter-gather.",
     "API Gateway aggregator becomes a single point of failure and compute bottleneck."),

    (126, "126-cqrs", "Command Query Responsibility Segregation (CQRS)",
     "Separating write-optimized transactional models from read-optimized view models.",
     "Read and write workloads often have fundamentally different scaling and schema needs.",
     "Single database schema serving both high-volume transactional writes and complex analytics queries.",
     "CQRS: Writes modify relational tables; asynchronous events update Elasticsearch read models.",
     "Complex reporting queries lock transactional tables, stalling order checkouts.",
     "Replication delay between write model and read model introduces eventual consistency."),

    (127, "127-event-sourcing", "Event Sourcing",
     "Storing state as an immutable sequence of append-only domain events.",
     "Current state is a transient projection calculated by replaying the event log from genesis.",
     "Overwriting account balance with `UPDATE accounts SET balance = ?`.",
     "Event Sourcing: appending `MoneyDeposited`, `MoneyWithdrawn` events to immutable log.",
     "Audit inquiry requires proving historical account balance at exact timestamp, but DB was overwritten.",
     "Replaying millions of events requires periodic snapshotting and complex schema migration."),

    (128, "128-materialized-views", "Materialized Views & Read Projections",
     "Pre-computing complex query results and storing them for instant retrieval.",
     "Trades write-time compute and storage for sub-millisecond read response times.",
     "Executing expensive multi-table aggregations on every user page load.",
     "Materialized view updated asynchronously via database triggers or stream processors.",
     "Complex aggregation query takes 3 seconds per page request.",
     "Materialized views consume additional storage and can return slightly stale data."),

    (129, "129-data-pipelines", "Data Pipelines & ETL Architecture",
     "Extracting, transforming, and loading operational transactional data into analytical lakes.",
     "Operational databases (OLTP) must be isolated from analytical reporting queries (OLAP).",
     "Running heavy marketing queries directly against the production primary database.",
     "CDC data pipeline streaming events from PostgreSQL into Snowflake / BigQuery.",
     "Marketing reporting query locks production database, causing customer timeouts.",
     "Data pipelines introduce pipeline lag and require data schema evolution management."),

    (130, "130-batch-vs-stream-processing", "Batch vs Stream Processing",
     "High-throughput periodic batch processing (Spark) vs real-time event streaming (Flink).",
     "Batch processing optimizes compute efficiency; streaming optimizes processing freshness.",
     "Running hourly batch jobs for fraud detection where immediate action is required.",
     "Real-time event streaming pipeline processing and scoring transactions in < 100ms.",
     "Fraudulent transaction detected 50 minutes after credit card was stolen.",
     "Stream processing infrastructure is more complex and operationally demanding than batch jobs."),

    (131, "131-scheduler-systems", "Distributed Task Schedulers",
     "Executing scheduled jobs (cron) reliably across distributed server clusters.",
     "Distributed schedulers require lease coordination to prevent duplicate job execution.",
     "Running standalone crontab on single application server.",
     "Distributed scheduler using database leases and heartbeat timers to assign jobs.",
     "Single server running cron crashes; all scheduled billing tasks fail silently.",
     "Requires clock synchronization and lease stealing recovery mechanisms."),

    (132, "132-notification-system-fundamentals", "Notification System Fundamentals",
     "Multi-channel dispatch (Email, SMS, Push) with user preference filtering and rate limits.",
     "Notification engines decouple application business logic from downstream delivery providers.",
     "Every microservice directly invoking Twilio / SendGrid APIs synchronously.",
     "Centralized notification service with template rendering, priority tiers, and provider failover.",
     "Twilio API outage causes checkout flow to fail.",
     "Requires managing user notification rate limits and unsubscription preferences."),

    (133, "133-presence-system", "Real-Time User Presence System",
     "Tracking online, offline, and away status for millions of concurrent users.",
     "Presence state is ephemeral; heartbeat leases with TTLs automatically handle abrupt client disconnects.",
     "Writing online status to relational database on every WebSocket ping.",
     "Redis key with 60-second TTL renewed by periodic client heartbeat pings.",
     "Database crashes under millions of heartbeat status updates.",
     "Client network blip causes temporary flicker between online and offline status."),

    (134, "134-leaderboard-system", "Real-Time Leaderboard System",
     "Ranking millions of user scores in real-time with sub-millisecond retrieval.",
     "Skip lists and sorted sets provide O(log N) score insertion and rank retrieval.",
     "Executing `SELECT rank() OVER (ORDER BY score DESC)` on relational database.",
     "Redis Sorted Sets (`ZADD`, `ZREVRANGE`, `ZREVRANK`) maintaining live ordered rankings.",
     "Relational database query takes 15 seconds sorting 10 million player records.",
     "Redis Sorted Sets are in-memory and consume RAM proportional to player count."),

    (135, "135-feed-generation", "Feed Generation: Push vs Pull",
     "Evaluating Fanout-on-Write (Push) vs Fanout-on-Read (Pull) for activity timelines.",
     "Push optimizes read latency; Pull optimizes write throughput for high-follower accounts.",
     "Pushing post to 50 million follower inboxes on every single tweet.",
     "Hybrid model: Push for regular users (< 10k followers); Pull on-read for celebrities.",
     "Celebrity tweets; write fanout takes 15 minutes, exhausting worker queue.",
     "Hybrid feed generation requires merging push timelines with pull streams on read."),

    (136, "136-hot-celebrity-problem", "The Celebrity Fanout Problem",
     "Handling users with 100M+ followers without overwhelming worker queues.",
     "Fanout-on-write breaks when follower counts approach millions.",
     "Uniform fanout-on-write for all user accounts.",
     "Celebrity posts stored in single author timeline; follower feeds fetch and merge on read.",
     "Celebrity post triggers 100 million inbox writes, crashing message broker.",
     "Merging feeds on read requires cache-aside read caching to keep latency low."),

    (137, "137-geospatial-systems", "Geospatial Indexing & Proximity Search",
     "Querying nearby drivers and restaurants using Geohash, Quadtree, and S2 Cells.",
     "Spatial partitioning reduces two-dimensional Euclidean distance queries to one-dimensional prefix lookups.",
     "Calculating bounding box distance with SQL `WHERE lat BETWEEN ... AND lng BETWEEN ...`.",
     "Geohash spatial indexing mapping latitude/longitude to hierarchical alphanumeric strings.",
     "Relational query scans millions of global records to find drivers within 5 km.",
     "Edge boundary anomalies: locations close in physical space may have different Geohash prefixes."),

    (138, "138-time-series-systems", "Time-Series Systems",
     "High-throughput append-only timestamped telemetry with automatic downsampling.",
     "Time-series workloads are write-heavy and append-only; queries scan contiguous time ranges.",
     "Writing server CPU metrics into standard normalized relational database tables.",
     "Time-partitioned tables (TimescaleDB / InfluxDB) with automated chunk dropping and rollups.",
     "Relational database runs out of disk storage holding 6 months of raw uncompressed metrics.",
     "Downsampled metrics lose fine-grained per-second spike visibility."),

    (139, "139-logging-system", "Distributed Log Aggregation Pipeline",
     "Collecting, buffering, and indexing terabytes of logs from thousands of microservices.",
     "Log ingestion pipelines must employ backpressure and buffering to survive traffic surges.",
     "Microservices writing logs directly over synchronous network sockets to central server.",
     "Local logging daemon (Fluentd) -> Kafka buffer -> OpenSearch indexing cluster.",
     "Central logging server crashes; all upstream application servers stall waiting on sockets.",
     "Log retention and full-text search indexing represent significant infrastructure cost."),

    (140, "140-metrics-system", "Metrics Collection & Storage System",
     "Pull-based (Prometheus) vs Push-based (StatsD) metric collection architectures.",
     "Push models risk overwhelming collectors; pull models provide built-in backpressure and discovery.",
     "Services pushing unthrottled metrics over UDP to overloaded collector.",
     "Pull-based scraping architecture with scrape intervals and target discovery.",
     "High-cardinality metric labels exhaust time-series memory.",
     "Pull scraping requires network accessibility from scraper to all application pods."),

    (141, "141-distributed-cache-system", "Distributed Cache System Architecture",
     "Designing a multi-node partitioned cache cluster with replication and failover.",
     "Consistent hashing distributes keys; read replicas scale read throughput across nodes.",
     "Single standalone Redis instance.",
     "Sharded Redis Cluster with 16,384 hash slots and primary-replica pairs.",
     "Standalone Redis host crashes, dropping all cached keys and crushing database.",
     "Cluster failover and slot migration add network management complexity."),

    (142, "142-blob-storage-system", "Distributed Blob Storage Architecture",
     "Designing an object storage system with chunking, manifests, and erasure coding.",
     "Erasure coding (Reed-Solomon) provides 11 nines durability with 50% storage overhead vs 200% for 3x replication.",
     "Storing entire 5 GB video files as single monolithic blobs on single disks.",
     "Chunking files into 64 MB blocks with chunk manifest metadata and erasure coding.",
     "Disk failure corrupts entire multi-gigabyte video file.",
     "Erasure coding adds CPU encode/decode compute overhead on reads and writes."),

    (143, "143-file-upload-service", "Resumable File Upload Architecture",
     "Uploading gigabyte-scale files over unstable networks using multipart pre-signed uploads.",
     "Chunked multipart uploads allow failed uploads to resume from the last successful chunk.",
     "Single HTTP POST uploading 10 GB file over mobile connection.",
     "Multipart upload: client requests pre-signed URLs per chunk and completes upload via manifest.",
     "Mobile connection drops at 99%; entire 10 GB upload fails and restarts from zero.",
     "Requires background cleanup workers to purge abandoned incomplete multipart uploads."),

    (144, "144-api-rate-limiter-design", "Enterprise Distributed Rate Limiter",
     "High-performance rate limiting using Redis token buckets with local memory caching.",
     "Multi-tier rate limiting: local in-memory filter rejects obvious floods; Redis coordinates globally.",
     "Querying centralized database counter on every incoming request.",
     "Two-tier rate limiter: local token cache + Redis cluster synchronized asynchronously.",
     "Central rate limiter latency increases API response time by 15ms.",
     "Local in-memory approximations may allow slight burst overruns during cluster sync."),

    (145, "145-distributed-lock-service", "Distributed Lock Service Architecture",
     "Building a fault-tolerant lock manager with leases, heartbeats, and fencing tokens.",
     "A lock service must guarantee mutual exclusion even during network partitions and GC pauses.",
     "Naive Redis `SETNX` without lease expiration or ownership verification.",
     "Consensus-backed lock service issuing monotonically increasing fencing tokens.",
     "Client process pauses for 15s; lock expires; two processes write concurrently.",
     "Fencing token validation requires downstream datastores to support conditional updates."),

    (146, "146-configuration-service", "Distributed Configuration Service",
     "Real-time dynamic configuration distribution (Consul / etcd model).",
     "Long-polling and watch notifications distribute config changes instantly without polling load.",
     "Hardcoded configuration files requiring service restarts to change settings.",
     "Centralized key-value configuration store with watch API and local client caching.",
     "Service restart during emergency feature flag toggle takes down production.",
     "Requires strong consistency to prevent nodes from running conflicting configurations."),

    (147, "147-service-discovery", "Service Discovery & Health Registries",
     "Dynamically tracking IP addresses of ephemeral cloud containers (Consul/K8s DNS).",
     "Client-side vs server-side discovery with automated heartbeat deregistration.",
     "Hardcoded static IP addresses in application configuration files.",
     "Service registry maintaining active instance addresses with automated health eviction.",
     "Container IP changes on reschedule; upstream callers send traffic to dead IP.",
     "DNS caching (TTL) can cause clients to route traffic to terminated instances."),

    (148, "148-feature-flag-system", "Feature Flag Management Platform",
     "Dynamic runtime experimentation, canary rollouts, and kill-switches.",
     "Feature flags must be evaluated in-memory (< 1ms) without blocking network roundtrips.",
     "Making network RPC call to feature flag server on every user request.",
     "Local rule evaluation engine with rules synced asynchronously via CDN/WebSocket.",
     "Feature flag server outage brings down the entire application.",
     "Stale local flag rules during the propagation window."),

    (149, "149-webhook-delivery-system", "Outbound Webhook Delivery Platform",
     "Delivering HTTP webhook notifications to third-party customer endpoints reliably.",
     "Outbound webhooks must handle slow endpoints, enforce timeouts, sign payloads, and isolate failures.",
     "Calling external customer webhook URLs synchronously inside order checkout handler.",
     "Dedicated webhook worker pool with per-domain rate limiting, HMAC-SHA256 signatures, and DLQs.",
     "Slow customer endpoint takes 30s to respond, exhausting internal worker threads.",
     "Requires managing per-tenant concurrency limits and exponential backoff retry schedules."),

    (150, "150-url-shortener", "Design a URL Shortener (TinyURL)",
     "Designing a high-throughput URL redirection service for 100 million links.",
     "Base62 encoding of 64-bit unique IDs; cache-aside read path optimizing 100:1 read ratio.",
     "Single server storing mappings in a flat text file.",
     "Stateless API instances, Base62 Snowflake IDs, PostgreSQL persistence, Redis cache.",
     "Database crashes under read surge of viral short link.",
     "Hash collisions or pre-generation requirements; cache invalidation on link updates."),

    (151, "151-pastebin", "Design Pastebin",
     "Text blob sharing service with TTL expiration and large payload handling.",
     "Separating metadata from text bytes; direct-to-object storage uploads for large pastes.",
     "Storing multi-megabyte code pastes as text fields in relational database tables.",
     "Relational metadata DB + S3 object store for text bytes + Redis cache for hot pastes.",
     "Database disk fills to capacity storing large raw code snippets.",
     "Eventual consistency between metadata creation and object upload completion."),

    (152, "152-tinyurl-at-large-scale", "TinyURL at Global Multi-Region Scale",
     "Evolving the URL shortener to handle 10 billion links and global multi-datacenter traffic.",
     "Geo-DNS routing, regional edge caches, and globally partitioned database clusters.",
     "Single-region database serving users across all continents.",
     "Multi-region deployment: Geo-DNS routing, local Redis edge caches, partitioned DB.",
     "Global users in Asia experience 300ms redirect latency to US datacenter.",
     "Cross-region replication conflicts and data transfer egress costs."),

    (153, "153-chat-system", "Design a 1-to-1 Real-Time Chat System",
     "Real-time bidirectional messaging, presence tracking, and offline message delivery.",
     "WebSocket connection management with user session registry and message sequencing.",
     "HTTP short polling querying database every 2 seconds for new messages.",
     "WebSocket gateway servers + Redis Pub/Sub routing + Cassandra message history store.",
     "Database crashes under millions of continuous HTTP polling requests.",
     "WebSocket connections are stateful, requiring sticky connection tracking and rebalance logic."),

    (154, "154-group-chat", "Design a Scalable Group Chat Platform",
     "Group membership management, message fanout, and read receipts for 10,000 members.",
     "Fanout-on-write to active group members; message ordering via room-scoped sequence numbers.",
     "Sending separate individual push notifications to all 10,000 members synchronously.",
     "Room message queues with batch fanout workers and client-side message reconciliation.",
     "Active group of 5,000 members freezes application server on every message sent.",
     "High fanout message volume increases broker network bandwidth and consumer memory."),

    (155, "155-notification-system", "Design a High-Volume Notification Platform",
     "Delivering billions of Push, SMS, and Email notifications across multiple third-party providers.",
     "Decoupling notification requests via prioritized queues with provider failover and rate limiting.",
     "Single synchronous worker dispatching emails and SMS directly.",
     "Tiered Kafka queues (Critical, Marketing) + multi-provider adapters + DLQs.",
     "Third-party SMS provider outage drops millions of multi-factor authentication codes.",
     "Handling duplicate notifications under at-least-once provider retries."),

    (156, "156-news-feed", "Design a Social Media News Feed",
     "Aggregating, ranking, and rendering personalized activity streams for 200M DAU.",
     "Hybrid fanout: fanout-on-write for regular users, fanout-on-read for high-follower accounts.",
     "Executing SQL query joining all followed users on every feed page load.",
     "Pre-computed Redis feed timelines populated by async workers upon post creation.",
     "Database CPU reaches 100% executing dynamic fanout-on-read queries across millions of rows.",
     "Pre-computed feeds consume substantial memory in distributed caches."),

    (157, "157-twitter-timeline", "Design Twitter/X Timeline with Celebrities",
     "Handling skewed follower distributions where accounts have 100M+ followers.",
     "Celebrity post fanout breaks write queues; timeline merger combines cached feed with celebrity stream.",
     "Writing celebrity tweet to 100 million user timelines on every post.",
     "Celebrity tweets stored in separate stream; client feed query merges local timeline with celebrity posts.",
     "Celebrity posts a tweet; message broker experiences 30-minute queue lag.",
     "Merging feeds at read time adds CPU compute overhead to the read path."),

    (158, "158-instagram-feed", "Design Instagram-Like Photo & Video Feed",
     "Media metadata storage, CDN edge delivery, and image thumbnail generation pipelines.",
     "Asynchronous media transcode workers generate multi-resolution assets stored in S3.",
     "Serving full-resolution 10 MB images directly from web server disk.",
     "Client uploads to S3 -> Async transcode worker -> Multi-resolution CDN distribution.",
     "Mobile clients crash and run out of data downloading uncompressed full-resolution media.",
     "High object storage and egress CDN costs for multi-resolution assets."),

    (159, "159-youtube-video-platform", "Design YouTube Video Platform",
     "Video upload, chunking, adaptive bitrate streaming (HLS/DASH), and metadata storage.",
     "Videos are split into chunks, transcoded in parallel into multiple bitrates, and served via CDN.",
     "Streaming single MP4 files directly from application web servers.",
     "Direct-to-S3 upload + distributed worker transcode pool + HLS manifest streaming + CDN.",
     "Web server network interface saturates streaming raw video files to users.",
     "Transcoding video requires substantial GPU/CPU compute cluster investments."),

    (160, "160-netflix-streaming", "Design Netflix-Like Global Streaming",
     "Open Connect appliance origin shielding, adaptive streaming, and playback telemetry.",
     "Custom CDN appliances deployed inside ISP networks deliver video without transit fees.",
     "Serving video streams across public internet backbones from central cloud datacenters.",
     "Custom ISP edge caching appliances (Open Connect) + client adaptive bitrate steering.",
     "Backbone network congestion causes video buffering and low-resolution fallback.",
     "Operating physical caching appliances inside third-party ISP datacenters is operationally complex."),

    (161, "161-dropbox-cloud-storage", "Design Dropbox / Google Drive",
     "Block-level file chunking, content-addressed deduplication, and cross-device synchronization.",
     "Chunking files into 4 MB blocks using rolling hashes; uploading only modified delta chunks.",
     "Uploading entire 1 GB file on every small text edit.",
     "Block chunking + SHA-256 content-addressing + metadata DB + sync protocol notifications.",
     "User edits 1 word in 100 MB file; entire file re-uploads, wasting bandwidth.",
     "Chunk-level deduplication requires maintaining a massive block index database."),

    (162, "162-search-autocomplete", "Design Search Autocomplete / Typeahead",
     "Sub-20ms prefix query suggestions using in-memory Trie structures and query frequency scoring.",
     "Tries pre-compute and cache top-5 completions at each node for instant prefix lookup.",
     "Executing SQL `SELECT query FROM searches WHERE query LIKE 'term%' ORDER BY count DESC`.",
     "Distributed in-memory Trie cluster partitioned by prefix characters + browser-side caching.",
     "Database table scan takes 500ms per keystroke as user types.",
     "Updating Trie frequencies in real-time requires offline map-reduce batch processing."),

    (163, "163-web-search-engine-overview", "Design a Web Search Engine",
     "Architecture of web crawlers, inverted index builders, PageRank scoring, and query serving.",
     "Separation of asynchronous indexing pipelines from low-latency distributed query servers.",
     "Monolithic search script running on a single computer.",
     "Distributed Crawler -> Document Parser -> MapReduce Index Builder -> Sharded Query Serving.",
     "Search queries take seconds scanning unindexed web pages.",
     "Maintaining fresh web indexes requires massive distributed crawling and storage infrastructure."),

    (164, "164-ride-sharing-system", "Design Uber / Lyft Ride-Sharing Engine",
     "Real-time driver location updates, spatial indexing, matching algorithms, and trip state.",
     "Geohash / Quadtree spatial indexing partitions drivers into regional cells for nearby queries.",
     "Calculating distance to all global drivers in relational database on every match request.",
     "Location update service (Redis Geospatial) + Geohash dispatch engine + trip state machine.",
     "Database crashes under 500,000 drivers sending GPS coordinates every 4 seconds.",
     "High driver location write frequency requires in-memory ephemeral datastores."),

    (165, "165-food-delivery", "Design DoorDash / UberEats Food Delivery",
     "Coordinating multi-actor workflows: Customer order, Restaurant preparation, Courier delivery.",
     "Saga orchestration manages order lifecycle with explicit timeouts and status state transitions.",
     "Direct uncoordinated HTTP calls between customer, restaurant, and driver apps.",
     "Saga Orchestrator + Geospatial courier assignment + real-time delivery tracking.",
     "Restaurant rejects order after customer card is charged; no automated compensation occurs.",
     "Complex multi-party state machine with high real-world edge cases (courier cancellation)."),

    (166, "166-ticket-booking", "Design Flash-Sale Ticket Booking (Ticketmaster)",
     "Preventing double-booking and overselling under extreme concurrent seat contention.",
     "Temporary hold locks with TTL expiration allow users 10 minutes to complete payment.",
     "Allowing direct checkouts without temporary holds, triggering race conditions.",
     "Distributed Redis hold reservation with TTL + relational ACID checkout transaction.",
     "Two concurrent buyers purchase the exact same concert seat simultaneously.",
     "Hold reservation timeouts must reliably release unpurchased inventory back to pool."),

    (167, "167-hotel-booking", "Design Hotel Room Booking Platform",
     "Managing room availability over contiguous date ranges under concurrent searches.",
     "Date-range availability indexing and optimistic concurrency checks prevent overbooking.",
     "Querying room availability by scanning individual date records across all rooms.",
     "Relational room-inventory table with composite key `(room_type_id, date)` and version checks.",
     "Concurrent bookings for overlapping date ranges double-book the same room.",
     "High search traffic scanning date ranges requires aggressive caching of availability grids."),

    (168, "168-ecommerce-platform", "Design an E-Commerce Transaction Platform",
     "Product catalog search, cart sessions, inventory reservation, and payment processing.",
     "Transactional Outbox pattern guarantees order record commit and inventory deduction.",
     "Separate non-transactional calls to update inventory and create order records.",
     "Relational ACID order boundary + Transactional Outbox + Redis cart cache.",
     "Inventory decrements, but payment fails; inventory remains lost.",
     "Pessimistic inventory locking reduces write throughput during flash sales."),

    (169, "169-payment-system", "Design a Distributed Payment System",
     "Idempotent payment processing, double-entry bookkeeping, and payment gateway state machines.",
     "Every financial transaction must record balanced debit and credit entries; operations must be idempotent.",
     "Single balance column updated via `UPDATE accounts SET balance = balance + 50`.",
     "Double-entry bookkeeping ledger + Idempotency store + reconciliation audit batch jobs.",
     "Network timeout on external payment gateway call causes double billing on retry.",
     "Strict financial auditability requires immutable append-only ledgers and reconciliation."),

    (170, "170-digital-wallet-ledger", "Design a Digital Wallet Platform",
     "High-throughput account ledger with immutable audit journals and derived balances.",
     "Account balances are derived from the sum of immutable ledger entries, preventing tampering.",
     "Mutable database rows updated in-place without audit trail.",
     "Immutable append-only ledger entries with periodic snapshot balance checkpoints.",
     "Database concurrency conflict under simultaneous transfers to the same hot wallet.",
     "High-frequency hot wallets (e.g. system accounts) require batching or balance sharding."),

    (171, "171-banking-transfer", "Design an Inter-Bank Wire Transfer System",
     "Cross-institution money transfers, ISO 20022 messaging, and settlement reconciliation.",
     "Two-Phase Commit or Saga compensation coordinating transfers across independent banking cores.",
     "Direct API transfer with no multi-stage settlement verification.",
     "Multi-stage transfer state machine: Initiated -> Funds Held -> Settled -> Completed.",
     "Transfer succeeds at source bank but target bank rejects transaction, stranding funds.",
     "Inter-bank settlement involves multi-day clearing windows and regulatory compliance."),

    (172, "172-stock-exchange-clob", "Design a Central Limit Order Book (CLOB)",
     "Sub-millisecond order matching engine using price-time priority queues.",
     "In-memory deterministic matching engines executing sequentially on dedicated CPU cores.",
     "Relational database queries matching buy and sell stock orders.",
     "In-memory price-time order book (B-Tree + Doubly Linked Lists) + sequenced event logging.",
     "Database transaction lock latency (10ms) causes massive order slippage and stale matching.",
     "In-memory matching engines must recover entire order book state from journal logs on crash."),

    (173, "173-ad-click-aggregation", "Design an Ad Click Aggregation Pipeline",
     "High-throughput event ingestion (100k clicks/s), deduplication, and windowed aggregation.",
     "Streaming map-reduce aggregates click counts in tumbling windows to minimize DB write load.",
     "Writing every raw ad impression directly to relational database table.",
     "Kafka event stream + Apache Flink tumbling window aggregator + Cassandra summary store.",
     "Database collapses under 100,000 raw click INSERTs per second.",
     "Windowed streaming aggregation introduces small analytical reporting delay."),

    (174, "174-analytics-pipeline", "Design an Enterprise Real-Time Analytics Pipeline",
     "Collecting operational events and streaming into columnar analytical datastores (ClickHouse).",
     "Columnar storage provides 100x compression and fast OLAP aggregation across billions of rows.",
     "Executing analytical aggregation queries (`SUM`, `AVG`, `GROUP BY`) on transactional DB.",
     "Event collector -> Kafka stream -> Columnar datastore (ClickHouse / Parquet / S3).",
     "Analytical query locks production transactional database during operational hours.",
     "Columnar datastores do not support low-latency point updates or ACID transactions."),

    (175, "175-distributed-job-scheduler", "Design a Distributed Job Scheduler",
     "Scheduling and executing millions of recurring tasks with distributed worker leases.",
     "Time-bucketed task queues and heartbeat leases guarantee at-least-once task execution.",
     "Single crontab process running on one virtual machine.",
     "Distributed scheduler: Partitioned task database + worker heartbeat leasing + retry manager.",
     "Worker crashes mid-task; task is marked in-progress forever and never completes.",
     "Ensuring tasks do not execute concurrently requires distributed coordination."),

    (176, "176-web-crawler", "Design a Distributed Web Crawler",
     "Scalable URL frontier, politeness rate limiting, robot.txt compliance, and content deduplication.",
     "URL frontier queues URLs by domain hostname to enforce politeness delays per web server.",
     "Multi-threaded crawler hammering single domain with 500 parallel requests, causing ban.",
     "Domain-partitioned URL frontier queues + politeness delayers + SimHash deduplication.",
     "Crawler downloads identical mirror pages under different URLs, wasting petabytes.",
     "Spider traps and dynamic infinite URLs require strict depth and URL length limits."),

    (177, "177-email-service", "Design an Enterprise Email Dispatch Platform",
     "Handling high-volume transactional and marketing email delivery with ISP reputation protection.",
     "Dedicated outbound IP pools, DKIM/SPF signing, rate throttling, and automated bounce handling.",
     "Sending marketing blasts directly from application server IP, resulting in immediate spam blacklisting.",
     "Prioritized dispatch queues + warm IP pools + DKIM/DMARC signing + bounce processing webhooks.",
     "High bounce rate ruins server reputation; legitimate customer password resets are blocked.",
     "Managing IP warm-up and delivery throttling per destination provider (Gmail, Yahoo)."),

    (178, "178-api-gateway", "Design an Enterprise API Gateway",
     "Unified perimeter gateway handling reverse proxying, JWT validation, rate limiting, and telemetry.",
     "Centralizes cross-cutting concerns so downstream microservices focus purely on domain logic.",
     "Every microservice independently implements rate limiting, TLS certificates, and auth tokens.",
     "Non-blocking asynchronous API Gateway (Envoy / Kong model) with dynamic service discovery.",
     "API Gateway becomes a CPU bottleneck under high cryptographic TLS handshake load.",
     "Gateway failure causes total cluster outage unless deployed in redundant multi-instance pools."),

    (179, "179-distributed-kv-store", "Design a Distributed Key-Value Store",
     "Building a fault-tolerant distributed key-value store using consistent hashing and quorum replication.",
     "Combines consistent hash ring partitioning, vector clocks, hinted handoff, and $N/W/R$ quorums.",
     "Single-node in-memory hash map.",
     "Distributed ring topology with virtual nodes, configurable quorums, and read repair.",
     "Node failure during write causes temporary data divergence across replicas.",
     "Eventual consistency requires background read repair and entropy synchronization (Merkle trees)."),

    (180, "180-design-review-discipline", "Design Review Discipline & Audit",
     "Mastering the 12-point architectural audit checklist before shipping systems to production.",
     "Systematic verification across requirements, scale, failure modes, consistency, observability, and cost.",
     "Deploying architecture without auditing single points of failure or recovery models.",
     "Comprehensive 12-point architectural review checklist evaluating every non-functional SLA.",
     "Unbudgeted cloud egress costs exceed company funding within 3 months of launch.",
     "Rigorous architectural review takes time but prevents catastrophic production rewrites."),

    (181, "181-architecture-evolution-challenges", "Architecture Evolution Under Scale",
     "Incrementally evolving a system under 10x read, 10x write, and multi-region pressure.",
     "Architectures must evolve in response to measured pressure, not speculative over-engineering.",
     "Over-engineering a system with Kafka and sharding before single-server limits are reached.",
     "Evolutionary architecture: 1 Machine -> Load Balancer -> Read Replicas -> Sharding -> Outbox.",
     "Premature microservice decomposition paralyzes early product feature development.",
     "Refactoring running production systems requires zero-downtime data migration techniques."),

    (182, "182-broken-architecture-challenges", "Diagnosing Broken Architectures",
     "Identifying critical flaws in distributed system diagrams and proposed interview solutions.",
     "Spotting anti-patterns: cache as source of truth, missing idempotency, unindexed fan-out.",
     "Approving an architecture diagram containing circular synchronous microservice calls.",
     "Systematic flaw diagnosis: tracing request flow, identifying SPOFs, and auditing failure paths.",
     "System fails in production due to a retry storm knocking down recovering databases.",
     "Fixing architectural anti-patterns often requires fundamental redesign of data flows."),

    (183, "183-tradeoff-challenges", "Real-World Architectural Tradeoff Scenarios",
     "Navigating difficult engineering compromises between consistency, latency, durability, and cost.",
     "There are no perfect architectures; every choice trades one operational property for another.",
     "Believing cloud vendor promises that a technology offers infinite scale with zero tradeoffs.",
     "Explicit tradeoff mapping: documenting chosen properties and explicitly accepted limitations.",
     "Choosing eventual consistency for a financial ledger causes balance reconciliation disputes.",
     "Tradeoffs must be aligned directly with product business priorities."),

    (184, "184-architecture-comparison", "100 QPS vs 100,000 QPS Architecture Comparison",
     "Comparing architectures for the same problem at startup scale vs global enterprise scale.",
     "The right architecture for 100 QPS is a liability at 100,000 QPS, and vice-versa.",
     "Building a 100,000 QPS architecture for a 100 QPS MVP application.",
     "Comparative architecture design: Simple single-server model vs Distributed partitioned cluster.",
     "Startup burns entire seed capital paying for Kubernetes cluster that handles 10 requests/minute.",
     "Scaling up requires redesigning persistence, caching, and communication layers."),

    (185, "185-interview-framework", "Mastering the System Design Interview",
     "Navigating the 45-minute collaborative system design interview conversation.",
     "An interview is an interactive engineering collaboration, not a memorized presentation.",
     "Drawing 20 boxes on the whiteboard within the first 5 minutes without clarifying scope.",
     "Disciplined 6-stage interview progression: Clarify -> Estimate -> API/Data -> Simple -> Scale -> Tradeoffs.",
     "Candidate fails interview because they designed a complex ML system when interviewer asked for storage API.",
     "Requires strong communication, quantitative mental math, and active listening skills."),

    (186, "186-interview-simulation-1", "Interview Simulation I: Global URL Shortener",
     "45-minute bounded design: Design a global URL shortener with 100M links and click analytics.",
     "Executing requirements gathering, scale calculation, Base62 encoding, and cache-aside design.",
     "Jumping immediately into distributed NoSQL databases without computing write QPS.",
     "Collaborative derivation: Single server baseline evolved to Redis cache and async analytics queue.",
     "Interviewer points out that click analytics writes will overwhelm the primary database.",
     "Balancing accurate analytics counting with low-latency link redirection."),

    (187, "187-interview-simulation-2", "Interview Simulation II: Changing Requirements",
     "Handling mid-interview requirement shifts: adapting to multi-region global traffic.",
     "Good system architects adapt their designs flexibly when business constraints change.",
     "Panicking or rigidly defending initial single-region design when interviewer changes constraints.",
     "Adaptive refactoring: introducing Geo-DNS, edge caches, and cross-region replication.",
     "Interviewer states: 'Now users are global and Europe requires < 50ms latency.'",
     "Cross-region replication introduces replication lag and potential write conflicts."),

    (188, "188-interview-simulation-3", "Interview Simulation III: Strict Consistency",
     "Designing under strict zero-overselling constraints: Flash-Sale Ticket Booking.",
     "Choosing strong consistency over availability when business invariants demand zero overselling.",
     "Using eventual consistency and asynchronous message queues for inventory checkout.",
     "Temporary reservation holds with Redis TTL + ACID database transaction with row-level locks.",
     "Interviewer asks: 'What happens if two users click buy on the last ticket simultaneously?'",
     "Pessimistic locking limits peak write throughput on hot inventory items."),

    (189, "189-interview-simulation-4", "Interview Simulation IV: 10x Traffic Surge",
     "Scaling a real-time social timeline when an event causes a 10x traffic explosion.",
     "Identifying the exact bottleneck under 10x load and scaling only that component.",
     "Suggesting a complete rewrite of all microservices under traffic surge.",
     "Targeted scaling: adding read replicas, hybrid feed generation, and aggressive edge caching.",
     "Interviewer states: 'A breaking news event causes read traffic to spike 10x in 2 minutes.'",
     "Aggressive caching introduces temporary timeline staleness."),

    (190, "190-interview-simulation-5", "Interview Simulation V: Cost-Constrained Architecture",
     "Designing a high-volume analytics system under a strict $500/month infrastructure budget.",
     "Cost is an architectural constraint; choosing efficient primitives over expensive managed services.",
     "Recommending multi-region Kafka and Snowflake clusters costing $10,000/month.",
     "Cost-optimized architecture: single Hetzner server with ClickHouse and local SSD storage.",
     "Interviewer states: 'Your infrastructure budget is capped at $500/month.'",
     "Single-server architectures require manual backup discipline and tolerate scheduled maintenance."),

    (191, "191-capstone-1-scalable-url-shortener", "Capstone 1: Scalable URL Shortener",
     "Full implementation: single process to PostgreSQL, Redis cache, and async analytics worker.",
     "Complete end-to-end realization of the canonical URL shortener system design.",
     "In-memory dictionary that loses data upon process restart.",
     "FastAPI gateway + Base62 Snowflake ID + SQLite/Postgres + Redis cache + async worker queue.",
     "Database crashes under high read traffic; cache-aside layer shields database.",
     "Cache invalidation on link deletion or metadata update."),

    (192, "192-capstone-2-event-driven-order-platform", "Capstone 2: Event-Driven Order Platform",
     "Full implementation: Orders API, Transactional Outbox, message queue, and independent workers.",
     "Eliminating dual-write bugs by staging outbox events in the same atomic database transaction.",
     "Direct HTTP calls from order handler to payment, inventory, and notification services.",
     "Orders API + SQLite WAL transaction + Outbox poller + Worker queue dispatch.",
     "Worker crashes mid-delivery; at-least-once delivery redelivers message safely.",
     "Requires idempotent consumers and outbox table polling cleanup."),

    (193, "193-capstone-3-real-time-chat", "Capstone 3: Real-Time Chat Platform",
     "Full implementation: WebSocket connection manager, presence tracking, and message history.",
     "Stateful WebSocket connection management with decoupled Pub/Sub broadcasting.",
     "HTTP polling for new chat messages.",
     "WebSocket connection manager + Redis room broadcast + durable message store.",
     "Client disconnects abruptly; heartbeat lease expires, marking user offline.",
     "Scaling stateful WebSocket servers requires cluster-wide connection registries."),

    (194, "194-capstone-4-distributed-cache-simulator", "Capstone 4: Distributed Cache Simulator",
     "Full implementation: Consistent hash ring, virtual nodes, replication, and node failover.",
     "Simulating a distributed in-memory cache cluster with dynamic topology management.",
     "Single monolithic cache instance.",
     "ConsistentHashRing with virtual nodes + primary-replica replication + failover handler.",
     "Node A crashes; traffic automatically remaps to replica without cluster wipeout.",
     "Virtual node traversal adds computational overhead to key routing."),

    (195, "195-capstone-5-distributed-queue-simulator", "Capstone 5: Distributed Queue Simulator",
     "Full implementation: Partitions, consumer groups, visibility timeouts, and DLQ routing.",
     "Simulating an enterprise message broker with partition leasing and failure isolation.",
     "Unpartitioned in-memory FIFO queue.",
     "Partitioned queue + consumer group offset tracker + visibility timeout + DLQ.",
     "Poison pill message crashes consumer; after 3 retries, message is isolated into DLQ.",
     "Partition count limits the maximum number of concurrent consumers in a group."),

    (196, "196-capstone-6-tiny-distributed-kv-store", "Capstone 6: Tiny Distributed KV Store",
     "Full implementation: Partitioned key-value storage with N/W/R quorums and hinted handoff.",
     "Demonstrating Dynamo-style leaderless replication and configurable consistency.",
     "Single-node key-value dictionary.",
     "Multi-node cluster with $N=3, W=2, R=2$ quorum read/write logic and hinted handoff buffer.",
     "One replica node goes down; writes succeed with $W=2$ quorum; hinted handoff replays upon recovery.",
     "Quorum reads require coordinating responses from multiple nodes, increasing read latency."),

    (197, "197-capstone-7-production-social-feed", "Capstone 7: Production-Like Social Feed",
     "Full implementation: Activity feed platform with hybrid fanout handling hot celebrity users.",
     "Combining fanout-on-write for standard users with fanout-on-read for high-follower accounts.",
     "Uniform fanout-on-write crashing workers on celebrity posts.",
     "Hybrid feed engine: standard posts pushed to follower inboxes; celebrity posts merged on read.",
     "Celebrity with 100k followers posts message; system bypasses write fanout without worker lag.",
     "Read-time feed merging requires multi-source caching and timeline sorting."),

    (198, "198-failure-day", "Failure Day: Chaos Testing Capstones",
     "Comprehensive chaos injection: injecting 8 failure modes into a running production capstone.",
     "Simulating real-world entropy: process crashes, network partitions, slow dependencies, and hot keys.",
     "Assuming systems will only fail in ways predicted by unit tests.",
     "Structured Chaos Day playbook: Predict -> Inject -> Observe -> Diagnose -> Recover -> Harden.",
     "Simulated database drop trips circuit breaker; system degrades gracefully without cascading.",
     "Resilience mechanisms add lines of code, configuration complexity, and testing burden."),

    (199, "199-architecture-review", "Architecture Review & Production Scorecard",
     "Comprehensive architectural scorecard evaluating systems across 11 non-functional pillars.",
     "Formal production readiness evaluation identifying operational risks prior to launch.",
     "Launching systems without reviewing failure containment, observability, or security posture.",
     "Production Readiness Review (PRR) scoring system: Correctness, HA, Latency, Durability, Cost.",
     "Audit reveals missing database backup snapshot schedule and unbounded queue buffers.",
     "Remediating architectural audit findings may require postponing initial launch dates."),

    (200, "200-final-design-challenge", "Final Design Challenge: Synthesis",
     "Independent end-to-end design: Globally Available Collaborative Document Service.",
     "Full synthesis of requirements, estimations, OT/CRDT concurrency, distributed storage, and tradeoffs.",
     "Immediately drawing microservices and cloud vendor logos.",
     "Rigorous first-principles design: Clarify -> Numbers -> Data/API -> Simple -> Scale -> Tradeoffs.",
     "Concurrent offline document edits resolve without data loss using causal conflict resolution.",
     "Collaborative real-time editing requires sophisticated conflict resolution and local state caching.")
]
